// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetVersion = `-- name: CreateAssetVersion :one
INSERT INTO asset_versions (project_id, version, action, stats_json, delta_json, note)
VALUES (
    $1, COALESCE($2, 1),
    COALESCE($3, 'freeze'),
    COALESCE($4, ''),
    COALESCE($5, ''),
    $6
)
RETURNING id, created_at, updated_at, deleted_at, project_id, version, action, stats_json, delta_json, note
`

type CreateAssetVersionParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Version   interface{} `json:"version"`
	Action    interface{} `json:"action"`
	StatsJson interface{} `json:"stats_json"`
	DeltaJson interface{} `json:"delta_json"`
	Note      pgtype.Text `json:"note"`
}

func (q *Queries) CreateAssetVersion(ctx context.Context, arg CreateAssetVersionParams) (AssetVersion, error) {
	row := q.db.QueryRow(ctx, createAssetVersion,
		arg.ProjectID,
		arg.Version,
		arg.Action,
		arg.StatsJson,
		arg.DeltaJson,
		arg.Note,
	)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Version,
		&i.Action,
		&i.StatsJson,
		&i.DeltaJson,
		&i.Note,
	)
	return i, err
}

const getLatestFreezeByProject = `-- name: GetLatestFreezeByProject :one
SELECT id, created_at, updated_at, deleted_at, project_id, version, action, stats_json, delta_json, note FROM asset_versions
WHERE project_id = $1 AND deleted_at IS NULL AND action = 'freeze'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestFreezeByProject(ctx context.Context, projectID pgtype.UUID) (AssetVersion, error) {
	row := q.db.QueryRow(ctx, getLatestFreezeByProject, projectID)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Version,
		&i.Action,
		&i.StatsJson,
		&i.DeltaJson,
		&i.Note,
	)
	return i, err
}

const listAssetVersionsByProject = `-- name: ListAssetVersionsByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, version, action, stats_json, delta_json, note FROM asset_versions
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListAssetVersionsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListAssetVersionsByProject(ctx context.Context, arg ListAssetVersionsByProjectParams) ([]AssetVersion, error) {
	rows, err := q.db.Query(ctx, listAssetVersionsByProject, arg.ProjectID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetVersion{}
	for rows.Next() {
		var i AssetVersion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.Version,
			&i.Action,
			&i.StatsJson,
			&i.DeltaJson,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
