// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: asset_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetVersion = `-- name: CreateAssetVersion :one
INSERT INTO asset_versions (asset_type, asset_id, project_id, version, snapshot_json, change_note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, asset_type, asset_id, project_id, version, snapshot_json, change_note, created_by
`

type CreateAssetVersionParams struct {
	AssetType    string      `json:"asset_type"`
	AssetID      pgtype.UUID `json:"asset_id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	Version      int32       `json:"version"`
	SnapshotJson []byte      `json:"snapshot_json"`
	ChangeNote   pgtype.Text `json:"change_note"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateAssetVersion(ctx context.Context, arg CreateAssetVersionParams) (AssetVersion, error) {
	row := q.db.QueryRow(ctx, createAssetVersion,
		arg.AssetType,
		arg.AssetID,
		arg.ProjectID,
		arg.Version,
		arg.SnapshotJson,
		arg.ChangeNote,
		arg.CreatedBy,
	)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AssetType,
		&i.AssetID,
		&i.ProjectID,
		&i.Version,
		&i.SnapshotJson,
		&i.ChangeNote,
		&i.CreatedBy,
	)
	return i, err
}

const getAssetVersion = `-- name: GetAssetVersion :one
SELECT id, created_at, asset_type, asset_id, project_id, version, snapshot_json, change_note, created_by FROM asset_versions WHERE id = $1
`

func (q *Queries) GetAssetVersion(ctx context.Context, id pgtype.UUID) (AssetVersion, error) {
	row := q.db.QueryRow(ctx, getAssetVersion, id)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AssetType,
		&i.AssetID,
		&i.ProjectID,
		&i.Version,
		&i.SnapshotJson,
		&i.ChangeNote,
		&i.CreatedBy,
	)
	return i, err
}

const getLatestAssetVersion = `-- name: GetLatestAssetVersion :one
SELECT id, created_at, asset_type, asset_id, project_id, version, snapshot_json, change_note, created_by FROM asset_versions WHERE asset_type = $1 AND asset_id = $2
ORDER BY version DESC LIMIT 1
`

type GetLatestAssetVersionParams struct {
	AssetType string      `json:"asset_type"`
	AssetID   pgtype.UUID `json:"asset_id"`
}

func (q *Queries) GetLatestAssetVersion(ctx context.Context, arg GetLatestAssetVersionParams) (AssetVersion, error) {
	row := q.db.QueryRow(ctx, getLatestAssetVersion, arg.AssetType, arg.AssetID)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.AssetType,
		&i.AssetID,
		&i.ProjectID,
		&i.Version,
		&i.SnapshotJson,
		&i.ChangeNote,
		&i.CreatedBy,
	)
	return i, err
}

const listAssetVersions = `-- name: ListAssetVersions :many
SELECT id, created_at, asset_type, asset_id, project_id, version, snapshot_json, change_note, created_by FROM asset_versions WHERE asset_type = $1 AND asset_id = $2
ORDER BY version DESC
`

type ListAssetVersionsParams struct {
	AssetType string      `json:"asset_type"`
	AssetID   pgtype.UUID `json:"asset_id"`
}

func (q *Queries) ListAssetVersions(ctx context.Context, arg ListAssetVersionsParams) ([]AssetVersion, error) {
	rows, err := q.db.Query(ctx, listAssetVersions, arg.AssetType, arg.AssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetVersion{}
	for rows.Next() {
		var i AssetVersion
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.AssetType,
			&i.AssetID,
			&i.ProjectID,
			&i.Version,
			&i.SnapshotJson,
			&i.ChangeNote,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
