// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character_snapshots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharacterSnapshot = `-- name: CreateCharacterSnapshot :one
INSERT INTO character_snapshots (character_id, project_id, prompt, negative_prompt, image_url, params_json, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, deleted_at, character_id, project_id, prompt, negative_prompt, image_url, params_json, status
`

type CreateCharacterSnapshotParams struct {
	CharacterID    pgtype.UUID `json:"character_id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Prompt         pgtype.Text `json:"prompt"`
	NegativePrompt pgtype.Text `json:"negative_prompt"`
	ImageUrl       pgtype.Text `json:"image_url"`
	ParamsJson     []byte      `json:"params_json"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) CreateCharacterSnapshot(ctx context.Context, arg CreateCharacterSnapshotParams) (CharacterSnapshot, error) {
	row := q.db.QueryRow(ctx, createCharacterSnapshot,
		arg.CharacterID,
		arg.ProjectID,
		arg.Prompt,
		arg.NegativePrompt,
		arg.ImageUrl,
		arg.ParamsJson,
		arg.Status,
	)
	var i CharacterSnapshot
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CharacterID,
		&i.ProjectID,
		&i.Prompt,
		&i.NegativePrompt,
		&i.ImageUrl,
		&i.ParamsJson,
		&i.Status,
	)
	return i, err
}

const deleteCharacterSnapshot = `-- name: DeleteCharacterSnapshot :exec
UPDATE character_snapshots SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCharacterSnapshot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCharacterSnapshot, id)
	return err
}

const getCharacterSnapshot = `-- name: GetCharacterSnapshot :one
SELECT id, created_at, updated_at, deleted_at, character_id, project_id, prompt, negative_prompt, image_url, params_json, status FROM character_snapshots WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCharacterSnapshot(ctx context.Context, id pgtype.UUID) (CharacterSnapshot, error) {
	row := q.db.QueryRow(ctx, getCharacterSnapshot, id)
	var i CharacterSnapshot
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CharacterID,
		&i.ProjectID,
		&i.Prompt,
		&i.NegativePrompt,
		&i.ImageUrl,
		&i.ParamsJson,
		&i.Status,
	)
	return i, err
}

const listCharacterSnapshotsByCharacter = `-- name: ListCharacterSnapshotsByCharacter :many
SELECT id, created_at, updated_at, deleted_at, character_id, project_id, prompt, negative_prompt, image_url, params_json, status FROM character_snapshots WHERE character_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListCharacterSnapshotsByCharacter(ctx context.Context, characterID pgtype.UUID) ([]CharacterSnapshot, error) {
	rows, err := q.db.Query(ctx, listCharacterSnapshotsByCharacter, characterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterSnapshot{}
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CharacterID,
			&i.ProjectID,
			&i.Prompt,
			&i.NegativePrompt,
			&i.ImageUrl,
			&i.ParamsJson,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharacterSnapshotsByProject = `-- name: ListCharacterSnapshotsByProject :many
SELECT id, created_at, updated_at, deleted_at, character_id, project_id, prompt, negative_prompt, image_url, params_json, status FROM character_snapshots WHERE project_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListCharacterSnapshotsByProject(ctx context.Context, projectID pgtype.UUID) ([]CharacterSnapshot, error) {
	rows, err := q.db.Query(ctx, listCharacterSnapshotsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharacterSnapshot{}
	for rows.Next() {
		var i CharacterSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CharacterID,
			&i.ProjectID,
			&i.Prompt,
			&i.NegativePrompt,
			&i.ImageUrl,
			&i.ParamsJson,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCharacterSnapshot = `-- name: UpdateCharacterSnapshot :exec
UPDATE character_snapshots SET prompt = $2, negative_prompt = $3, image_url = $4, params_json = $5, status = $6
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateCharacterSnapshotParams struct {
	ID             pgtype.UUID `json:"id"`
	Prompt         pgtype.Text `json:"prompt"`
	NegativePrompt pgtype.Text `json:"negative_prompt"`
	ImageUrl       pgtype.Text `json:"image_url"`
	ParamsJson     []byte      `json:"params_json"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) UpdateCharacterSnapshot(ctx context.Context, arg UpdateCharacterSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateCharacterSnapshot,
		arg.ID,
		arg.Prompt,
		arg.NegativePrompt,
		arg.ImageUrl,
		arg.ParamsJson,
		arg.Status,
	)
	return err
}
