// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: composite_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompositeTask = `-- name: CreateCompositeTask :one

INSERT INTO composite_tasks (project_id, episode_id, task_id, status, output_url, config_json, error_msg)
VALUES (
    $1, $2, $3,
    COALESCE($4, 'pending'), $5,
    COALESCE($6, '{}'), $7
)
RETURNING id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg
`

type CreateCompositeTaskParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EpisodeID  pgtype.UUID `json:"episode_id"`
	TaskID     pgtype.Text `json:"task_id"`
	Status     interface{} `json:"status"`
	OutputUrl  pgtype.Text `json:"output_url"`
	ConfigJson interface{} `json:"config_json"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

// 成片任务 CRUD（README 成片阶段，状态机 editing→exporting→done）
func (q *Queries) CreateCompositeTask(ctx context.Context, arg CreateCompositeTaskParams) (CompositeTask, error) {
	row := q.db.QueryRow(ctx, createCompositeTask,
		arg.ProjectID,
		arg.EpisodeID,
		arg.TaskID,
		arg.Status,
		arg.OutputUrl,
		arg.ConfigJson,
		arg.ErrorMsg,
	)
	var i CompositeTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const getCompositeTaskByID = `-- name: GetCompositeTaskByID :one
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM composite_tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompositeTaskByID(ctx context.Context, id pgtype.UUID) (CompositeTask, error) {
	row := q.db.QueryRow(ctx, getCompositeTaskByID, id)
	var i CompositeTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const getCompositeTaskByTaskID = `-- name: GetCompositeTaskByTaskID :one
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM composite_tasks
WHERE task_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompositeTaskByTaskID(ctx context.Context, taskID pgtype.Text) (CompositeTask, error) {
	row := q.db.QueryRow(ctx, getCompositeTaskByTaskID, taskID)
	var i CompositeTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const listCompositeTasksByEpisode = `-- name: ListCompositeTasksByEpisode :many
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM composite_tasks
WHERE episode_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCompositeTasksByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]CompositeTask, error) {
	rows, err := q.db.Query(ctx, listCompositeTasksByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositeTask{}
	for rows.Next() {
		var i CompositeTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.EpisodeID,
			&i.TaskID,
			&i.Status,
			&i.OutputUrl,
			&i.ConfigJson,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompositeTasksByProject = `-- name: ListCompositeTasksByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM composite_tasks
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCompositeTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]CompositeTask, error) {
	rows, err := q.db.Query(ctx, listCompositeTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositeTask{}
	for rows.Next() {
		var i CompositeTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.EpisodeID,
			&i.TaskID,
			&i.Status,
			&i.OutputUrl,
			&i.ConfigJson,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCompositeTask = `-- name: SoftDeleteCompositeTask :exec
UPDATE composite_tasks SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteCompositeTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCompositeTask, id)
	return err
}

const updateCompositeTaskID = `-- name: UpdateCompositeTaskID :exec
UPDATE composite_tasks SET task_id = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateCompositeTaskIDParams struct {
	TaskID pgtype.Text `json:"task_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCompositeTaskID(ctx context.Context, arg UpdateCompositeTaskIDParams) error {
	_, err := q.db.Exec(ctx, updateCompositeTaskID, arg.TaskID, arg.ID)
	return err
}

const updateCompositeTaskStatus = `-- name: UpdateCompositeTaskStatus :one
UPDATE composite_tasks
SET status = COALESCE($1, status),
    output_url = COALESCE($2, output_url),
    error_msg = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg
`

type UpdateCompositeTaskStatusParams struct {
	Status    pgtype.Text `json:"status"`
	OutputUrl pgtype.Text `json:"output_url"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCompositeTaskStatus(ctx context.Context, arg UpdateCompositeTaskStatusParams) (CompositeTask, error) {
	row := q.db.QueryRow(ctx, updateCompositeTaskStatus,
		arg.Status,
		arg.OutputUrl,
		arg.ErrorMsg,
		arg.ID,
	)
	var i CompositeTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}
