// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateSegments implements pgx.CopyFromSource.
type iteratorForBulkCreateSegments struct {
	rows                 []BulkCreateSegmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateSegments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateSegments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].SortIndex,
		r.rows[0].Content,
	}, nil
}

func (r iteratorForBulkCreateSegments) Err() error {
	return nil
}

func (q *Queries) BulkCreateSegments(ctx context.Context, arg []BulkCreateSegmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"segments"}, []string{"project_id", "sort_index", "content"}, &iteratorForBulkCreateSegments{rows: arg})
}
