// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLocation = `-- name: CreateLocation :one

INSERT INTO locations (
    project_id, name, "time", interior_exterior, atmosphere, color_tone,
    layout, style, style_override, style_note, image_status, status, source
)
VALUES (
    $1, $2, COALESCE($3, ''),
    COALESCE($4, ''), COALESCE($5, ''),
    COALESCE($6, ''), COALESCE($7, ''),
    COALESCE($8, ''), COALESCE($9, false),
    COALESCE($10, ''), COALESCE($11, 'none'),
    COALESCE($12, 'draft'), COALESCE($13, 'manual')
)
RETURNING id, created_at, updated_at, deleted_at, project_id, name, time, interior_exterior, atmosphere, color_tone, layout, style, style_id, style_override, style_note, image_url, reference_images_json, task_id, image_status, status, source
`

type CreateLocationParams struct {
	ProjectID        pgtype.UUID `json:"project_id"`
	Name             string      `json:"name"`
	Time             interface{} `json:"time"`
	InteriorExterior interface{} `json:"interior_exterior"`
	Atmosphere       interface{} `json:"atmosphere"`
	ColorTone        interface{} `json:"color_tone"`
	Layout           interface{} `json:"layout"`
	Style            interface{} `json:"style"`
	StyleOverride    interface{} `json:"style_override"`
	StyleNote        interface{} `json:"style_note"`
	ImageStatus      interface{} `json:"image_status"`
	Status           interface{} `json:"status"`
	Source           interface{} `json:"source"`
}

// 场景资产 CRUD（项目级）
func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ProjectID,
		arg.Name,
		arg.Time,
		arg.InteriorExterior,
		arg.Atmosphere,
		arg.ColorTone,
		arg.Layout,
		arg.Style,
		arg.StyleOverride,
		arg.StyleNote,
		arg.ImageStatus,
		arg.Status,
		arg.Source,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Time,
		&i.InteriorExterior,
		&i.Atmosphere,
		&i.ColorTone,
		&i.Layout,
		&i.Style,
		&i.StyleID,
		&i.StyleOverride,
		&i.StyleNote,
		&i.ImageUrl,
		&i.ReferenceImagesJson,
		&i.TaskID,
		&i.ImageStatus,
		&i.Status,
		&i.Source,
	)
	return i, err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, created_at, updated_at, deleted_at, project_id, name, time, interior_exterior, atmosphere, color_tone, layout, style, style_id, style_override, style_note, image_url, reference_images_json, task_id, image_status, status, source FROM locations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLocationByID(ctx context.Context, id pgtype.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Time,
		&i.InteriorExterior,
		&i.Atmosphere,
		&i.ColorTone,
		&i.Layout,
		&i.Style,
		&i.StyleID,
		&i.StyleOverride,
		&i.StyleNote,
		&i.ImageUrl,
		&i.ReferenceImagesJson,
		&i.TaskID,
		&i.ImageStatus,
		&i.Status,
		&i.Source,
	)
	return i, err
}

const listLocationsByProject = `-- name: ListLocationsByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, name, time, interior_exterior, atmosphere, color_tone, layout, style, style_id, style_override, style_note, image_url, reference_images_json, task_id, image_status, status, source FROM locations
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListLocationsByProject(ctx context.Context, projectID pgtype.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.Name,
			&i.Time,
			&i.InteriorExterior,
			&i.Atmosphere,
			&i.ColorTone,
			&i.Layout,
			&i.Style,
			&i.StyleID,
			&i.StyleOverride,
			&i.StyleNote,
			&i.ImageUrl,
			&i.ReferenceImagesJson,
			&i.TaskID,
			&i.ImageStatus,
			&i.Status,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLocation = `-- name: SoftDeleteLocation :exec
UPDATE locations SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteLocation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteLocation, id)
	return err
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET
    name = COALESCE($1, name),
    "time" = COALESCE($2, "time"),
    interior_exterior = COALESCE($3, interior_exterior),
    atmosphere = COALESCE($4, atmosphere),
    color_tone = COALESCE($5, color_tone),
    layout = COALESCE($6, layout),
    style = COALESCE($7, style),
    style_override = COALESCE($8, style_override),
    style_note = COALESCE($9, style_note),
    image_url = COALESCE($10, image_url),
    reference_images_json = COALESCE($11, reference_images_json),
    status = COALESCE($12, status)
WHERE id = $13 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, name, time, interior_exterior, atmosphere, color_tone, layout, style, style_id, style_override, style_note, image_url, reference_images_json, task_id, image_status, status, source
`

type UpdateLocationParams struct {
	Name                pgtype.Text `json:"name"`
	Time                pgtype.Text `json:"time"`
	InteriorExterior    pgtype.Text `json:"interior_exterior"`
	Atmosphere          pgtype.Text `json:"atmosphere"`
	ColorTone           pgtype.Text `json:"color_tone"`
	Layout              pgtype.Text `json:"layout"`
	Style               pgtype.Text `json:"style"`
	StyleOverride       pgtype.Bool `json:"style_override"`
	StyleNote           pgtype.Text `json:"style_note"`
	ImageUrl            pgtype.Text `json:"image_url"`
	ReferenceImagesJson []byte      `json:"reference_images_json"`
	Status              pgtype.Text `json:"status"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocation,
		arg.Name,
		arg.Time,
		arg.InteriorExterior,
		arg.Atmosphere,
		arg.ColorTone,
		arg.Layout,
		arg.Style,
		arg.StyleOverride,
		arg.StyleNote,
		arg.ImageUrl,
		arg.ReferenceImagesJson,
		arg.Status,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Time,
		&i.InteriorExterior,
		&i.Atmosphere,
		&i.ColorTone,
		&i.Layout,
		&i.Style,
		&i.StyleID,
		&i.StyleOverride,
		&i.StyleNote,
		&i.ImageUrl,
		&i.ReferenceImagesJson,
		&i.TaskID,
		&i.ImageStatus,
		&i.Status,
		&i.Source,
	)
	return i, err
}

const updateLocationImage = `-- name: UpdateLocationImage :one
UPDATE locations
SET image_url = COALESCE($1, image_url),
    task_id = COALESCE($2, task_id),
    image_status = COALESCE($3, image_status)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, name, time, interior_exterior, atmosphere, color_tone, layout, style, style_id, style_override, style_note, image_url, reference_images_json, task_id, image_status, status, source
`

type UpdateLocationImageParams struct {
	ImageUrl    pgtype.Text `json:"image_url"`
	TaskID      pgtype.Text `json:"task_id"`
	ImageStatus pgtype.Text `json:"image_status"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateLocationImage(ctx context.Context, arg UpdateLocationImageParams) (Location, error) {
	row := q.db.QueryRow(ctx, updateLocationImage,
		arg.ImageUrl,
		arg.TaskID,
		arg.ImageStatus,
		arg.ID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Time,
		&i.InteriorExterior,
		&i.Atmosphere,
		&i.ColorTone,
		&i.Layout,
		&i.Style,
		&i.StyleID,
		&i.StyleOverride,
		&i.StyleNote,
		&i.ImageUrl,
		&i.ReferenceImagesJson,
		&i.TaskID,
		&i.ImageStatus,
		&i.Status,
		&i.Source,
	)
	return i, err
}
