// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetVersion struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AssetType    string             `json:"asset_type"`
	AssetID      pgtype.UUID        `json:"asset_id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Version      int32              `json:"version"`
	SnapshotJson []byte             `json:"snapshot_json"`
	ChangeNote   pgtype.Text        `json:"change_note"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

type Character struct {
	ID                   pgtype.UUID        `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	ProjectID            pgtype.UUID        `json:"project_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	Name                 string             `json:"name"`
	AliasJson            []byte             `json:"alias_json"`
	Appearance           pgtype.Text        `json:"appearance"`
	Style                pgtype.Text        `json:"style"`
	StyleID              pgtype.UUID        `json:"style_id"`
	StyleOverride        bool               `json:"style_override"`
	Personality          pgtype.Text        `json:"personality"`
	VoiceHint            pgtype.Text        `json:"voice_hint"`
	Emotions             pgtype.Text        `json:"emotions"`
	Scenes               pgtype.Text        `json:"scenes"`
	Gender               pgtype.Text        `json:"gender"`
	AgeGroup             pgtype.Text        `json:"age_group"`
	VoiceID              pgtype.Text        `json:"voice_id"`
	VoiceName            pgtype.Text        `json:"voice_name"`
	ImageUrl             pgtype.Text        `json:"image_url"`
	ReferenceImagesJson  []byte             `json:"reference_images_json"`
	TaskID               pgtype.Text        `json:"task_id"`
	ImageStatus          pgtype.Text        `json:"image_status"`
	Shared               bool               `json:"shared"`
	Status               string             `json:"status"`
	Source               string             `json:"source"`
	VariantsJson         []byte             `json:"variants_json"`
	Importance           pgtype.Text        `json:"importance"`
	Consistency          pgtype.Text        `json:"consistency"`
	RoleType             pgtype.Text        `json:"role_type"`
	TagsJson             []byte             `json:"tags_json"`
	PropsJson            []byte             `json:"props_json"`
	Bio                  pgtype.Text        `json:"bio"`
	BioFragmentsJson     []byte             `json:"bio_fragments_json"`
	ImageGenOverrideJson []byte             `json:"image_gen_override_json"`
	Version              int32              `json:"version"`
}

type CharacterSnapshot struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CharacterID    pgtype.UUID        `json:"character_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Prompt         pgtype.Text        `json:"prompt"`
	NegativePrompt pgtype.Text        `json:"negative_prompt"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	ParamsJson     []byte             `json:"params_json"`
	Status         pgtype.Text        `json:"status"`
}

type CompositeTask struct {
	ID                 pgtype.UUID        `json:"id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ProjectID          pgtype.UUID        `json:"project_id"`
	EpisodeID          pgtype.UUID        `json:"episode_id"`
	Status             string             `json:"status"`
	TimelineJson       []byte             `json:"timeline_json"`
	AudioTracksJson    []byte             `json:"audio_tracks_json"`
	SubtitleTracksJson []byte             `json:"subtitle_tracks_json"`
	OutputUrl          pgtype.Text        `json:"output_url"`
	OutputFormat       pgtype.Text        `json:"output_format"`
	Resolution         pgtype.Text        `json:"resolution"`
	Duration           int32              `json:"duration"`
	Progress           int32              `json:"progress"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
}

type Episode struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Title        pgtype.Text        `json:"title"`
	SortIndex    int32              `json:"sort_index"`
	Summary      pgtype.Text        `json:"summary"`
	Status       string             `json:"status"`
	CurrentStep  int32              `json:"current_step"`
	CurrentPhase string             `json:"current_phase"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
}

type Location struct {
	ID                  pgtype.UUID        `json:"id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Name                string             `json:"name"`
	Time                pgtype.Text        `json:"time"`
	InteriorExterior    pgtype.Text        `json:"interior_exterior"`
	Atmosphere          pgtype.Text        `json:"atmosphere"`
	ColorTone           pgtype.Text        `json:"color_tone"`
	Layout              pgtype.Text        `json:"layout"`
	Style               pgtype.Text        `json:"style"`
	StyleID             pgtype.UUID        `json:"style_id"`
	StyleOverride       bool               `json:"style_override"`
	StyleNote           pgtype.Text        `json:"style_note"`
	ImageUrl            pgtype.Text        `json:"image_url"`
	ReferenceImagesJson []byte             `json:"reference_images_json"`
	TaskID              pgtype.Text        `json:"task_id"`
	ImageStatus         pgtype.Text        `json:"image_status"`
	Status              pgtype.Text        `json:"status"`
	Source              pgtype.Text        `json:"source"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Content   pgtype.Text        `json:"content"`
	RefType   pgtype.Text        `json:"ref_type"`
	RefID     pgtype.UUID        `json:"ref_id"`
	IsRead    bool               `json:"is_read"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
}

type OrgMember struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Name      string             `json:"name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	Plan      pgtype.Text        `json:"plan"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
}

type Project struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	Story          pgtype.Text        `json:"story"`
	StoryMode      pgtype.Text        `json:"story_mode"`
	ConfigJson     []byte             `json:"config_json"`
	PropsJson      []byte             `json:"props_json"`
	StoryboardJson []byte             `json:"storyboard_json"`
	MirrorMode     bool               `json:"mirror_mode"`
	TeamID         pgtype.UUID        `json:"team_id"`
	Visibility     pgtype.Text        `json:"visibility"`
	Version        int32              `json:"version"`
	StoryLocked    bool               `json:"story_locked"`
	StoryLockedAt  pgtype.Timestamptz `json:"story_locked_at"`
	AssetsLocked   bool               `json:"assets_locked"`
	AssetsLockedAt pgtype.Timestamptz `json:"assets_locked_at"`
	ScriptLocked   bool               `json:"script_locked"`
	ScriptLockedAt pgtype.Timestamptz `json:"script_locked_at"`
}

type ProjectMember struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	RolesJson []byte             `json:"roles_json"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type Prop struct {
	ID                  pgtype.UUID        `json:"id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Name                string             `json:"name"`
	Appearance          pgtype.Text        `json:"appearance"`
	IsKeyProp           bool               `json:"is_key_prop"`
	Style               pgtype.Text        `json:"style"`
	StyleID             pgtype.UUID        `json:"style_id"`
	StyleOverride       bool               `json:"style_override"`
	ReferenceImagesJson []byte             `json:"reference_images_json"`
	ImageUrl            pgtype.Text        `json:"image_url"`
	UsedByJson          []byte             `json:"used_by_json"`
	ScenesJson          []byte             `json:"scenes_json"`
	Status              pgtype.Text        `json:"status"`
	Source              pgtype.Text        `json:"source"`
}

type ProviderUsage struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	Capability   string             `json:"capability"`
	InputTokens  int32              `json:"input_tokens"`
	OutputTokens int32              `json:"output_tokens"`
	ImageCount   int32              `json:"image_count"`
	VideoSeconds int32              `json:"video_seconds"`
	AudioSeconds int32              `json:"audio_seconds"`
	CostCents    int32              `json:"cost_cents"`
	TaskID       pgtype.Text        `json:"task_id"`
	MetadataJson []byte             `json:"metadata_json"`
}

type ReviewConfig struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Phase     string             `json:"phase"`
	Mode      string             `json:"mode"`
	AiModel   pgtype.Text        `json:"ai_model"`
	AiPrompt  pgtype.Text        `json:"ai_prompt"`
}

type ReviewRecord struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	Phase        string             `json:"phase"`
	TargetType   string             `json:"target_type"`
	TargetID     pgtype.UUID        `json:"target_id"`
	ReviewerType string             `json:"reviewer_type"`
	ReviewerID   pgtype.UUID        `json:"reviewer_id"`
	Status       string             `json:"status"`
	AiScore      pgtype.Int4        `json:"ai_score"`
	AiReason     pgtype.Text        `json:"ai_reason"`
	HumanComment pgtype.Text        `json:"human_comment"`
	Round        int32              `json:"round"`
	DecidedAt    pgtype.Timestamptz `json:"decided_at"`
}

type Scene struct {
	ID               pgtype.UUID        `json:"id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	EpisodeID        pgtype.UUID        `json:"episode_id"`
	SceneID          pgtype.Text        `json:"scene_id"`
	Location         pgtype.Text        `json:"location"`
	Time             pgtype.Text        `json:"time"`
	InteriorExterior pgtype.Text        `json:"interior_exterior"`
	CharactersJson   []byte             `json:"characters_json"`
	SortIndex        int32              `json:"sort_index"`
}

type SceneBlock struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	SceneID   pgtype.UUID        `json:"scene_id"`
	Type      string             `json:"type"`
	Character pgtype.Text        `json:"character"`
	Emotion   pgtype.Text        `json:"emotion"`
	Content   string             `json:"content"`
	SortIndex int32              `json:"sort_index"`
}

type Schedule struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Name           string             `json:"name"`
	CronExpr       string             `json:"cron_expr"`
	TaskType       string             `json:"task_type"`
	TaskParamsJson []byte             `json:"task_params_json"`
	Enabled        bool               `json:"enabled"`
	LastRunAt      pgtype.Timestamptz `json:"last_run_at"`
	NextRunAt      pgtype.Timestamptz `json:"next_run_at"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
}

type Segment struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ProjectID pgtype.UUID        `json:"project_id"`
	SortIndex int32              `json:"sort_index"`
	Content   pgtype.Text        `json:"content"`
}

type Shot struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	SegmentID      pgtype.UUID        `json:"segment_id"`
	SceneID        pgtype.UUID        `json:"scene_id"`
	SortIndex      int32              `json:"sort_index"`
	Prompt         pgtype.Text        `json:"prompt"`
	StylePrompt    pgtype.Text        `json:"style_prompt"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	VideoUrl       pgtype.Text        `json:"video_url"`
	TaskID         pgtype.Text        `json:"task_id"`
	Status         string             `json:"status"`
	Duration       int32              `json:"duration"`
	CameraType     pgtype.Text        `json:"camera_type"`
	CameraAngle    pgtype.Text        `json:"camera_angle"`
	Dialogue       pgtype.Text        `json:"dialogue"`
	CharacterName  pgtype.Text        `json:"character_name"`
	CharacterID    pgtype.UUID        `json:"character_id"`
	Emotion        pgtype.Text        `json:"emotion"`
	Voice          pgtype.Text        `json:"voice"`
	VoiceName      pgtype.Text        `json:"voice_name"`
	LipSync        pgtype.Text        `json:"lip_sync"`
	Transition     pgtype.Text        `json:"transition"`
	AudioDesign    pgtype.Text        `json:"audio_design"`
	Priority       pgtype.Text        `json:"priority"`
	NegativePrompt pgtype.Text        `json:"negative_prompt"`
	Version        int32              `json:"version"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	ReviewStatus   pgtype.Text        `json:"review_status"`
	ReviewComment  pgtype.Text        `json:"review_comment"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
}

type ShotImage struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ShotID         pgtype.UUID        `json:"shot_id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	ImageUrl       string             `json:"image_url"`
	TaskID         pgtype.Text        `json:"task_id"`
	Status         string             `json:"status"`
	Provider       pgtype.Text        `json:"provider"`
	Model          pgtype.Text        `json:"model"`
	Prompt         pgtype.Text        `json:"prompt"`
	NegativePrompt pgtype.Text        `json:"negative_prompt"`
	ParamsJson     []byte             `json:"params_json"`
	Version        int32              `json:"version"`
	ReviewStatus   pgtype.Text        `json:"review_status"`
	ReviewComment  pgtype.Text        `json:"review_comment"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
}

type ShotVideo struct {
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ShotID        pgtype.UUID        `json:"shot_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ShotImageID   pgtype.UUID        `json:"shot_image_id"`
	VideoUrl      string             `json:"video_url"`
	TaskID        pgtype.Text        `json:"task_id"`
	Status        string             `json:"status"`
	Duration      int32              `json:"duration"`
	Provider      pgtype.Text        `json:"provider"`
	Model         pgtype.Text        `json:"model"`
	ParamsJson    []byte             `json:"params_json"`
	Version       int32              `json:"version"`
	ReviewStatus  pgtype.Text        `json:"review_status"`
	ReviewComment pgtype.Text        `json:"review_comment"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
}

type Style struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Category       pgtype.Text        `json:"category"`
	PreviewUrl     pgtype.Text        `json:"preview_url"`
	PromptTemplate pgtype.Text        `json:"prompt_template"`
	NegativePrompt pgtype.Text        `json:"negative_prompt"`
	ParamsJson     []byte             `json:"params_json"`
	Status         pgtype.Text        `json:"status"`
	Source         pgtype.Text        `json:"source"`
}

type TaskLock struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Action       string             `json:"action"`
	Status       string             `json:"status"`
	LockedBy     pgtype.UUID        `json:"locked_by"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
}

type TeamMember struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Role         string             `json:"role"`
}
