// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, link_url, meta_json)
VALUES (
    $1, COALESCE($2, 'task_complete'),
    $3, COALESCE($4, ''),
    $5, COALESCE($6, '{}')
)
RETURNING id, created_at, user_id, type, title, body, link_url, read_at, meta_json
`

type CreateNotificationParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Type     interface{} `json:"type"`
	Title    string      `json:"title"`
	Body     interface{} `json:"body"`
	LinkUrl  pgtype.Text `json:"link_url"`
	MetaJson interface{} `json:"meta_json"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.LinkUrl,
		arg.MetaJson,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.LinkUrl,
		&i.ReadAt,
		&i.MetaJson,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, created_at, user_id, type, title, body, link_url, read_at, meta_json FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.LinkUrl,
			&i.ReadAt,
			&i.MetaJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllAsReadByUser = `-- name: MarkAllAsReadByUser :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllAsReadByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllAsReadByUser, userID)
	return err
}

const markAsRead = `-- name: MarkAsRead :exec
UPDATE notifications SET read_at = now()
WHERE id = $1 AND user_id = $2
`

type MarkAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkAsRead(ctx context.Context, arg MarkAsReadParams) error {
	_, err := q.db.Exec(ctx, markAsRead, arg.ID, arg.UserID)
	return err
}
