// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, project_id, type, title, content, ref_type, ref_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, user_id, project_id, type, title, content, ref_type, ref_id, is_read, read_at
`

type CreateNotificationParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Type      string      `json:"type"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
	RefType   pgtype.Text `json:"ref_type"`
	RefID     pgtype.UUID `json:"ref_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.RefType,
		arg.RefID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.RefType,
		&i.RefID,
		&i.IsRead,
		&i.ReadAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, created_at, user_id, project_id, type, title, content, ref_type, ref_id, is_read, read_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.RefType,
			&i.RefID,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, created_at, user_id, project_id, type, title, content, ref_type, ref_id, is_read, read_at FROM notifications WHERE user_id = $1 AND is_read = false ORDER BY created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.RefType,
			&i.RefID,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = true, read_at = now() WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET is_read = true, read_at = now() WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}
