// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_members (org_id, user_id, role, joined_at)
VALUES (
    $1,
    $2,
    COALESCE($3, 'member'),
    now()
)
RETURNING id, created_at, updated_at, deleted_at, org_id, user_id, role, joined_at
`

type AddOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   interface{} `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, avatar_url, plan, owner_id)
VALUES (
    $1,
    COALESCE($2, ''),
    COALESCE($3, 'free'),
    $4
)
RETURNING id, created_at, updated_at, deleted_at, name, avatar_url, plan, owner_id
`

type CreateOrganizationParams struct {
	Name      string      `json:"name"`
	AvatarUrl interface{} `json:"avatar_url"`
	Plan      interface{} `json:"plan"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.AvatarUrl,
		arg.Plan,
		arg.OwnerID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.OwnerID,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
UPDATE organizations SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, created_at, updated_at, deleted_at, name, avatar_url, plan, owner_id FROM organizations
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrgByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.OwnerID,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT id, created_at, updated_at, deleted_at, org_id, user_id, role, joined_at FROM org_members
WHERE org_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.id, om.created_at, om.updated_at, om.deleted_at, om.org_id, om.user_id, om.role, om.joined_at, u.username, u.display_name FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = $1 AND om.deleted_at IS NULL
ORDER BY om.created_at ASC
`

type ListOrgMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	OrgID       pgtype.UUID        `json:"org_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsByUser = `-- name: ListOrgsByUser :many
SELECT o.id, o.created_at, o.updated_at, o.deleted_at, o.name, o.avatar_url, o.plan, o.owner_id FROM organizations o
JOIN org_members om ON om.org_id = o.id AND om.deleted_at IS NULL
WHERE om.user_id = $1 AND o.deleted_at IS NULL
UNION
SELECT o.id, o.created_at, o.updated_at, o.deleted_at, o.name, o.avatar_url, o.plan, o.owner_id FROM organizations o
WHERE o.owner_id = $1 AND o.deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOrgsByUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrgsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.AvatarUrl,
			&i.Plan,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
UPDATE org_members SET deleted_at = now()
WHERE org_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type RemoveOrgMemberParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = COALESCE($1, name),
    avatar_url = COALESCE($2, avatar_url),
    plan = COALESCE($3, plan)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, name, avatar_url, plan, owner_id
`

type UpdateOrganizationParams struct {
	Name      pgtype.Text `json:"name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Plan      pgtype.Text `json:"plan"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.Name,
		arg.AvatarUrl,
		arg.Plan,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.AvatarUrl,
		&i.Plan,
		&i.OwnerID,
	)
	return i, err
}
