// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package_tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPackageTask = `-- name: CreatePackageTask :one

INSERT INTO package_tasks (project_id, episode_id, task_id, status, output_url, config_json, error_msg)
VALUES (
    $1, $2, $3,
    COALESCE($4, 'pending'), $5,
    COALESCE($6, '{}'), $7
)
RETURNING id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg
`

type CreatePackageTaskParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EpisodeID  pgtype.UUID `json:"episode_id"`
	TaskID     pgtype.Text `json:"task_id"`
	Status     interface{} `json:"status"`
	OutputUrl  pgtype.Text `json:"output_url"`
	ConfigJson interface{} `json:"config_json"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

// 按集打包任务 CRUD（README 2.7）
func (q *Queries) CreatePackageTask(ctx context.Context, arg CreatePackageTaskParams) (PackageTask, error) {
	row := q.db.QueryRow(ctx, createPackageTask,
		arg.ProjectID,
		arg.EpisodeID,
		arg.TaskID,
		arg.Status,
		arg.OutputUrl,
		arg.ConfigJson,
		arg.ErrorMsg,
	)
	var i PackageTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const getPackageTaskByID = `-- name: GetPackageTaskByID :one
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM package_tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPackageTaskByID(ctx context.Context, id pgtype.UUID) (PackageTask, error) {
	row := q.db.QueryRow(ctx, getPackageTaskByID, id)
	var i PackageTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const getPackageTaskByTaskID = `-- name: GetPackageTaskByTaskID :one
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM package_tasks
WHERE task_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPackageTaskByTaskID(ctx context.Context, taskID pgtype.Text) (PackageTask, error) {
	row := q.db.QueryRow(ctx, getPackageTaskByTaskID, taskID)
	var i PackageTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}

const listPackageTasksByEpisode = `-- name: ListPackageTasksByEpisode :many
SELECT id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg FROM package_tasks
WHERE episode_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPackageTasksByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]PackageTask, error) {
	rows, err := q.db.Query(ctx, listPackageTasksByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PackageTask{}
	for rows.Next() {
		var i PackageTask
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.EpisodeID,
			&i.TaskID,
			&i.Status,
			&i.OutputUrl,
			&i.ConfigJson,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageTaskID = `-- name: UpdatePackageTaskID :exec
UPDATE package_tasks SET task_id = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdatePackageTaskIDParams struct {
	TaskID pgtype.Text `json:"task_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePackageTaskID(ctx context.Context, arg UpdatePackageTaskIDParams) error {
	_, err := q.db.Exec(ctx, updatePackageTaskID, arg.TaskID, arg.ID)
	return err
}

const updatePackageTaskStatus = `-- name: UpdatePackageTaskStatus :one
UPDATE package_tasks
SET status = COALESCE($1, status),
    output_url = COALESCE($2, output_url),
    error_msg = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, episode_id, task_id, status, output_url, config_json, error_msg
`

type UpdatePackageTaskStatusParams struct {
	Status    pgtype.Text `json:"status"`
	OutputUrl pgtype.Text `json:"output_url"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePackageTaskStatus(ctx context.Context, arg UpdatePackageTaskStatusParams) (PackageTask, error) {
	row := q.db.QueryRow(ctx, updatePackageTaskStatus,
		arg.Status,
		arg.OutputUrl,
		arg.ErrorMsg,
		arg.ID,
	)
	var i PackageTask
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.EpisodeID,
		&i.TaskID,
		&i.Status,
		&i.OutputUrl,
		&i.ConfigJson,
		&i.ErrorMsg,
	)
	return i, err
}
