// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectMember = `-- name: CreateProjectMember :one
INSERT INTO project_members (project_id, user_id, role, joined_at)
VALUES ($1, $2, COALESCE($3, 'viewer'), $4)
RETURNING id, created_at, updated_at, deleted_at, project_id, user_id, role, roles_json, joined_at
`

type CreateProjectMemberParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      interface{}        `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, createProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.RolesJson,
		&i.JoinedAt,
	)
	return i, err
}

const getProjectMemberByProjectAndUser = `-- name: GetProjectMemberByProjectAndUser :one
SELECT id, created_at, updated_at, deleted_at, project_id, user_id, role, roles_json, joined_at FROM project_members
WHERE project_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetProjectMemberByProjectAndUserParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMemberByProjectAndUser(ctx context.Context, arg GetProjectMemberByProjectAndUserParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMemberByProjectAndUser, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.RolesJson,
		&i.JoinedAt,
	)
	return i, err
}

const listProjectMembersByProject = `-- name: ListProjectMembersByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, user_id, role, roles_json, joined_at FROM project_members
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY role ASC
`

func (q *Queries) ListProjectMembersByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.RolesJson,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProjectMember = `-- name: SoftDeleteProjectMember :exec
UPDATE project_members
SET deleted_at = now()
WHERE project_id = $1 AND user_id = $2
`

type SoftDeleteProjectMemberParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteProjectMember(ctx context.Context, arg SoftDeleteProjectMemberParams) error {
	_, err := q.db.Exec(ctx, softDeleteProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
UPDATE project_members
SET role = COALESCE($1, role)
WHERE project_id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, user_id, role, roles_json, joined_at
`

type UpdateProjectMemberRoleParams struct {
	Role      pgtype.Text `json:"role"`
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.Role, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.RolesJson,
		&i.JoinedAt,
	)
	return i, err
}
