// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestProjectEventID = `-- name: GetLatestProjectEventID :one
SELECT COALESCE(MAX(id), 0)::bigint AS last_id FROM project_events
WHERE project_id = $1
`

// 获取项目最新事件 ID（供 WebSocket 连接时返回起点）
func (q *Queries) GetLatestProjectEventID(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLatestProjectEventID, projectID)
	var last_id int64
	err := row.Scan(&last_id)
	return last_id, err
}

const insertProjectEvent = `-- name: InsertProjectEvent :one
INSERT INTO project_events (project_id, task_id, user_id, event_type, target_type, target_id, payload)
VALUES (
    $1, $2, $3,
    $4,
    $5, $6,
    COALESCE($7, '{}'::jsonb)
)
RETURNING id, project_id, task_id, user_id, event_type, target_type, target_id, payload, created_at
`

type InsertProjectEventParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	TaskID     pgtype.Text `json:"task_id"`
	UserID     pgtype.UUID `json:"user_id"`
	EventType  string      `json:"event_type"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.Text `json:"target_id"`
	Payload    interface{} `json:"payload"`
}

// 插入项目事件，返回 id（即 seq）供实时推送附带
func (q *Queries) InsertProjectEvent(ctx context.Context, arg InsertProjectEventParams) (ProjectEvent, error) {
	row := q.db.QueryRow(ctx, insertProjectEvent,
		arg.ProjectID,
		arg.TaskID,
		arg.UserID,
		arg.EventType,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	var i ProjectEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.UserID,
		&i.EventType,
		&i.TargetType,
		&i.TargetID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectEventsAfter = `-- name: ListProjectEventsAfter :many
SELECT id, project_id, task_id, user_id, event_type, target_type, target_id, payload, created_at FROM project_events
WHERE project_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListProjectEventsAfterParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AfterID   int64       `json:"after_id"`
	Lim       int32       `json:"lim"`
}

// 按项目补拉事件（WebSocket 重连后调用）
func (q *Queries) ListProjectEventsAfter(ctx context.Context, arg ListProjectEventsAfterParams) ([]ProjectEvent, error) {
	rows, err := q.db.Query(ctx, listProjectEventsAfter, arg.ProjectID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectEvent{}
	for rows.Next() {
		var i ProjectEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.UserID,
			&i.EventType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentProjectEvents = `-- name: ListRecentProjectEvents :many
SELECT id, project_id, task_id, user_id, event_type, target_type, target_id, payload, created_at FROM project_events
WHERE project_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListRecentProjectEventsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Lim       int32       `json:"lim"`
}

// 查询项目内最近 N 条事件（首次连接快照）
func (q *Queries) ListRecentProjectEvents(ctx context.Context, arg ListRecentProjectEventsParams) ([]ProjectEvent, error) {
	rows, err := q.db.Query(ctx, listRecentProjectEvents, arg.ProjectID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectEvent{}
	for rows.Next() {
		var i ProjectEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.UserID,
			&i.EventType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskEventsAfter = `-- name: ListTaskEventsAfter :many
SELECT id, project_id, task_id, user_id, event_type, target_type, target_id, payload, created_at FROM project_events
WHERE task_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListTaskEventsAfterParams struct {
	TaskID  pgtype.Text `json:"task_id"`
	AfterID int64       `json:"after_id"`
	Lim     int32       `json:"lim"`
}

// 按任务补拉事件（单次执行的过程详情）
func (q *Queries) ListTaskEventsAfter(ctx context.Context, arg ListTaskEventsAfterParams) ([]ProjectEvent, error) {
	rows, err := q.db.Query(ctx, listTaskEventsAfter, arg.TaskID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectEvent{}
	for rows.Next() {
		var i ProjectEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.UserID,
			&i.EventType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEventsAfter = `-- name: ListUserEventsAfter :many
SELECT id, project_id, task_id, user_id, event_type, target_type, target_id, payload, created_at FROM project_events
WHERE user_id = $1 AND project_id IS NULL AND id > $2
ORDER BY id
LIMIT $3
`

type ListUserEventsAfterParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	AfterID int64       `json:"after_id"`
	Lim     int32       `json:"lim"`
}

// 按用户补拉无项目归属的事件（素材任务等）
func (q *Queries) ListUserEventsAfter(ctx context.Context, arg ListUserEventsAfterParams) ([]ProjectEvent, error) {
	rows, err := q.db.Query(ctx, listUserEventsAfter, arg.UserID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectEvent{}
	for rows.Next() {
		var i ProjectEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.UserID,
			&i.EventType,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
