// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error)
	ApplyStyleToCharacters(ctx context.Context, arg ApplyStyleToCharactersParams) ([]pgtype.UUID, error)
	ApplyStyleToLocations(ctx context.Context, arg ApplyStyleToLocationsParams) ([]pgtype.UUID, error)
	ApplyStyleToProps(ctx context.Context, arg ApplyStyleToPropsParams) ([]pgtype.UUID, error)
	BatchCancelTasks(ctx context.Context, ids []pgtype.UUID) error
	BulkCreateSegments(ctx context.Context, arg []BulkCreateSegmentsParams) (int64, error)
	CancelTask(ctx context.Context, id pgtype.UUID) (Task, error)
	ClearProjectDefault(ctx context.Context, projectID pgtype.UUID) error
	CountEpisodesByProject(ctx context.Context, projectID pgtype.UUID) (int32, error)
	CountResourcesByLibraryType(ctx context.Context, arg CountResourcesByLibraryTypeParams) ([]CountResourcesByLibraryTypeRow, error)
	CountResourcesByUser(ctx context.Context, arg CountResourcesByUserParams) (int64, error)
	CountSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) (int32, error)
	CountScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) (int32, error)
	CountShotsByProject(ctx context.Context, projectID pgtype.UUID) (int32, error)
	CountTasksByProject(ctx context.Context, projectID pgtype.UUID) (int64, error)
	CountUnreadByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateAssetVersion(ctx context.Context, arg CreateAssetVersionParams) (AssetVersion, error)
	// 角色 CRUD（项目级）
	CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error)
	// 成片任务 CRUD（README 成片阶段，状态机 editing→exporting→done）
	CreateCompositeTask(ctx context.Context, arg CreateCompositeTaskParams) (CompositeTask, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	// 场景资产 CRUD（项目级）
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// 按集打包任务 CRUD（README 2.7）
	CreatePackageTask(ctx context.Context, arg CreatePackageTaskParams) (PackageTask, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (ProjectMember, error)
	// 道具资产 CRUD（项目级）
	CreateProp(ctx context.Context, arg CreatePropParams) (Prop, error)
	CreateProviderUsage(ctx context.Context, arg CreateProviderUsageParams) (ProviderUsage, error)
	// 素材库 CRUD（用户级）
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	// 审核记录 CRUD（README 2.2 审核闭环、状态机、反馈给生产 AI）
	CreateReviewRecord(ctx context.Context, arg CreateReviewRecordParams) (ReviewRecord, error)
	CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error)
	CreateSceneBlock(ctx context.Context, arg CreateSceneBlockParams) (SceneBlock, error)
	// 定时任务 CRUD（README 2.1 定时任务、按计划触发流水线）
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	// 脚本分段 CRUD（项目级）
	CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error)
	// 镜头 CRUD（脚本指令，项目级）
	CreateShot(ctx context.Context, arg CreateShotParams) (Shot, error)
	// 镜图 CRUD（每个镜头的关键帧图像）
	CreateShotImage(ctx context.Context, arg CreateShotImageParams) (ShotImage, error)
	// 镜头视频 CRUD（每个镜头的视频片段）
	CreateShotVideo(ctx context.Context, arg CreateShotVideoParams) (ShotVideo, error)
	// 风格 CRUD（项目级，阶段 3）
	CreateStyle(ctx context.Context, arg CreateStyleParams) (Style, error)
	// 统一任务 CRUD（README §2.1 任务编排，前端任务中心）
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrganization(ctx context.Context, id pgtype.UUID) error
	DeleteSchedule(ctx context.Context, id pgtype.UUID) error
	ExistsUserByUsername(ctx context.Context, username string) (bool, error)
	GetCharacterByID(ctx context.Context, id pgtype.UUID) (Character, error)
	GetCharacterByNameAndProject(ctx context.Context, arg GetCharacterByNameAndProjectParams) (Character, error)
	GetCompositeTaskByID(ctx context.Context, id pgtype.UUID) (CompositeTask, error)
	GetCompositeTaskByTaskID(ctx context.Context, taskID pgtype.Text) (CompositeTask, error)
	GetEpisodeByID(ctx context.Context, id pgtype.UUID) (Episode, error)
	GetLatestFreezeByProject(ctx context.Context, projectID pgtype.UUID) (AssetVersion, error)
	GetLocationByID(ctx context.Context, id pgtype.UUID) (Location, error)
	GetOrgByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetPackageTaskByID(ctx context.Context, id pgtype.UUID) (PackageTask, error)
	GetPackageTaskByTaskID(ctx context.Context, taskID pgtype.Text) (PackageTask, error)
	GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectByIDAndUser(ctx context.Context, arg GetProjectByIDAndUserParams) (Project, error)
	GetProjectMemberByProjectAndUser(ctx context.Context, arg GetProjectMemberByProjectAndUserParams) (ProjectMember, error)
	GetPropByID(ctx context.Context, id pgtype.UUID) (Prop, error)
	GetResourceByID(ctx context.Context, id pgtype.UUID) (Resource, error)
	GetResourceByIDAndUser(ctx context.Context, arg GetResourceByIDAndUserParams) (Resource, error)
	GetSceneBlockByID(ctx context.Context, id pgtype.UUID) (SceneBlock, error)
	GetSceneByID(ctx context.Context, id pgtype.UUID) (Scene, error)
	GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error)
	GetSegmentByID(ctx context.Context, id pgtype.UUID) (Segment, error)
	GetShotByID(ctx context.Context, id pgtype.UUID) (Shot, error)
	GetShotImageByID(ctx context.Context, id pgtype.UUID) (ShotImage, error)
	GetShotVideoByID(ctx context.Context, id pgtype.UUID) (ShotVideo, error)
	GetShotVideoByShotPrimary(ctx context.Context, shotID pgtype.UUID) (ShotVideo, error)
	GetStyleByID(ctx context.Context, id pgtype.UUID) (Style, error)
	GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error)
	GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error)
	GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAssetVersionsByProject(ctx context.Context, arg ListAssetVersionsByProjectParams) ([]AssetVersion, error)
	ListCharactersByProject(ctx context.Context, projectID pgtype.UUID) ([]Character, error)
	ListCharactersByUser(ctx context.Context, userID pgtype.UUID) ([]Character, error)
	ListCharactersByUserWithShared(ctx context.Context, userID pgtype.UUID) ([]Character, error)
	ListCompositeTasksByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]CompositeTask, error)
	ListCompositeTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]CompositeTask, error)
	ListDueSchedules(ctx context.Context) ([]Schedule, error)
	ListEpisodesByProject(ctx context.Context, projectID pgtype.UUID) ([]Episode, error)
	ListLocationsByProject(ctx context.Context, projectID pgtype.UUID) ([]Location, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error)
	ListOrgsByUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error)
	ListPackageTasksByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]PackageTask, error)
	ListProjectMembersByProject(ctx context.Context, projectID pgtype.UUID) ([]ProjectMember, error)
	ListProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	ListProjectsByUserOrMember(ctx context.Context, userID pgtype.UUID) ([]Project, error)
	ListPropsByProject(ctx context.Context, projectID pgtype.UUID) ([]Prop, error)
	// AI 用量统计（README 8.3 AI 成本控制）
	ListProviderUsages(ctx context.Context, arg ListProviderUsagesParams) ([]ProviderUsage, error)
	ListResourcesByUser(ctx context.Context, arg ListResourcesByUserParams) ([]Resource, error)
	ListReviewRecordsByTarget(ctx context.Context, arg ListReviewRecordsByTargetParams) ([]ReviewRecord, error)
	ListSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) ([]SceneBlock, error)
	ListSceneBlocksBySceneIDs(ctx context.Context, sceneIds []pgtype.UUID) ([]SceneBlock, error)
	ListScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]Scene, error)
	ListScenesByProject(ctx context.Context, projectID pgtype.UUID) ([]Scene, error)
	ListSchedulesByProject(ctx context.Context, projectID pgtype.UUID) ([]Schedule, error)
	ListSegmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Segment, error)
	ListShotImagesByProject(ctx context.Context, projectID pgtype.UUID) ([]ShotImage, error)
	ListShotImagesByShot(ctx context.Context, shotID pgtype.UUID) ([]ShotImage, error)
	ListShotVideosByProject(ctx context.Context, projectID pgtype.UUID) ([]ShotVideo, error)
	ListShotVideosByShot(ctx context.Context, shotID pgtype.UUID) ([]ShotVideo, error)
	ListShotsByProject(ctx context.Context, projectID pgtype.UUID) ([]Shot, error)
	ListShotsByScene(ctx context.Context, sceneID pgtype.UUID) ([]Shot, error)
	ListShotsBySegment(ctx context.Context, segmentID pgtype.UUID) ([]Shot, error)
	ListStylesByProject(ctx context.Context, projectID pgtype.UUID) ([]Style, error)
	ListTasksByIDs(ctx context.Context, ids []pgtype.UUID) ([]Task, error)
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	ListTasksByProjectAndStatus(ctx context.Context, arg ListTasksByProjectAndStatusParams) ([]Task, error)
	ListTasksByProjectAndType(ctx context.Context, arg ListTasksByProjectAndTypeParams) ([]Task, error)
	ListTasksByProjectTypeAndStatus(ctx context.Context, arg ListTasksByProjectTypeAndStatusParams) ([]Task, error)
	ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error)
	ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error)
	ListTeamsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkAllAsReadByUser(ctx context.Context, userID pgtype.UUID) error
	MarkAsRead(ctx context.Context, arg MarkAsReadParams) error
	ReleaseExpiredShotLocks(ctx context.Context) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	SetProjectDefault(ctx context.Context, arg SetProjectDefaultParams) error
	SoftDeleteCharacter(ctx context.Context, id pgtype.UUID) error
	SoftDeleteCompositeTask(ctx context.Context, id pgtype.UUID) error
	SoftDeleteEpisode(ctx context.Context, id pgtype.UUID) error
	SoftDeleteEpisodesByProject(ctx context.Context, projectID pgtype.UUID) error
	SoftDeleteLocation(ctx context.Context, id pgtype.UUID) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error
	SoftDeleteProjectMember(ctx context.Context, arg SoftDeleteProjectMemberParams) error
	SoftDeleteProp(ctx context.Context, id pgtype.UUID) error
	SoftDeleteResource(ctx context.Context, arg SoftDeleteResourceParams) error
	SoftDeleteScene(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSceneBlock(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) error
	SoftDeleteScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) error
	SoftDeleteSegment(ctx context.Context, id pgtype.UUID) error
	SoftDeleteSegmentsByProject(ctx context.Context, projectID pgtype.UUID) error
	SoftDeleteShot(ctx context.Context, id pgtype.UUID) error
	SoftDeleteShotImage(ctx context.Context, id pgtype.UUID) error
	SoftDeleteShotImagesByShot(ctx context.Context, shotID pgtype.UUID) error
	SoftDeleteShotVideo(ctx context.Context, id pgtype.UUID) error
	SoftDeleteShotVideosByShot(ctx context.Context, shotID pgtype.UUID) error
	SoftDeleteShotsByProject(ctx context.Context, projectID pgtype.UUID) error
	SoftDeleteStyle(ctx context.Context, id pgtype.UUID) error
	SoftDeleteTeam(ctx context.Context, id pgtype.UUID) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	// 尝试加锁：仅当未锁、或本人持有、或超时(1h)时可加锁
	TryLockShot(ctx context.Context, arg TryLockShotParams) (pgtype.UUID, error)
	UnlockShot(ctx context.Context, arg UnlockShotParams) error
	UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error)
	UpdateCharacterImage(ctx context.Context, arg UpdateCharacterImageParams) (Character, error)
	UpdateCompositeTaskID(ctx context.Context, arg UpdateCompositeTaskIDParams) error
	UpdateCompositeTaskStatus(ctx context.Context, arg UpdateCompositeTaskStatusParams) (CompositeTask, error)
	UpdateEpisode(ctx context.Context, arg UpdateEpisodeParams) (Episode, error)
	UpdateEpisodeSortIndex(ctx context.Context, arg UpdateEpisodeSortIndexParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateLocationImage(ctx context.Context, arg UpdateLocationImageParams) (Location, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdatePackageTaskID(ctx context.Context, arg UpdatePackageTaskIDParams) error
	UpdatePackageTaskStatus(ctx context.Context, arg UpdatePackageTaskStatusParams) (PackageTask, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectMemberJobRoles(ctx context.Context, arg UpdateProjectMemberJobRolesParams) (ProjectMember, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (ProjectMember, error)
	UpdateProp(ctx context.Context, arg UpdatePropParams) (Prop, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error)
	UpdateSceneBlock(ctx context.Context, arg UpdateSceneBlockParams) (SceneBlock, error)
	UpdateSceneBlockSortIndex(ctx context.Context, arg UpdateSceneBlockSortIndexParams) error
	UpdateSceneSortIndex(ctx context.Context, arg UpdateSceneSortIndexParams) error
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateScheduleRunTimes(ctx context.Context, arg UpdateScheduleRunTimesParams) error
	UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error)
	UpdateSegmentSortIndex(ctx context.Context, arg UpdateSegmentSortIndexParams) error
	UpdateShot(ctx context.Context, arg UpdateShotParams) (Shot, error)
	UpdateShotImage(ctx context.Context, arg UpdateShotImageParams) (ShotImage, error)
	UpdateShotImageResult(ctx context.Context, arg UpdateShotImageResultParams) (Shot, error)
	UpdateShotImageReview(ctx context.Context, arg UpdateShotImageReviewParams) (ShotImage, error)
	UpdateShotImageStatus(ctx context.Context, arg UpdateShotImageStatusParams) (ShotImage, error)
	UpdateShotReview(ctx context.Context, arg UpdateShotReviewParams) (Shot, error)
	UpdateShotSortIndex(ctx context.Context, arg UpdateShotSortIndexParams) error
	UpdateShotVideo(ctx context.Context, arg UpdateShotVideoParams) (ShotVideo, error)
	UpdateShotVideoResult(ctx context.Context, arg UpdateShotVideoResultParams) (Shot, error)
	UpdateShotVideoReview(ctx context.Context, arg UpdateShotVideoReviewParams) (ShotVideo, error)
	UpdateShotVideoStatus(ctx context.Context, arg UpdateShotVideoStatusParams) (ShotVideo, error)
	UpdateStyle(ctx context.Context, arg UpdateStyleParams) (Style, error)
	UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error)
	UpdateTaskResult(ctx context.Context, arg UpdateTaskResultParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) (TeamMember, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
