// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResourcesByLibraryType = `-- name: CountResourcesByLibraryType :many
SELECT library_type, COUNT(*)::bigint as count
FROM resources
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR modality = $2)
GROUP BY library_type
`

type CountResourcesByLibraryTypeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Modality pgtype.Text `json:"modality"`
}

type CountResourcesByLibraryTypeRow struct {
	LibraryType string `json:"library_type"`
	Count       int64  `json:"count"`
}

func (q *Queries) CountResourcesByLibraryType(ctx context.Context, arg CountResourcesByLibraryTypeParams) ([]CountResourcesByLibraryTypeRow, error) {
	rows, err := q.db.Query(ctx, countResourcesByLibraryType, arg.UserID, arg.Modality)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountResourcesByLibraryTypeRow{}
	for rows.Next() {
		var i CountResourcesByLibraryTypeRow
		if err := rows.Scan(&i.LibraryType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countResourcesByUser = `-- name: CountResourcesByUser :one
SELECT COUNT(*)::bigint FROM resources
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR modality = $2)
  AND ($3::text IS NULL OR library_type = $3)
  AND ($4::jsonb IS NULL OR tags_json && $4::jsonb)
`

type CountResourcesByUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Modality    pgtype.Text `json:"modality"`
	LibraryType pgtype.Text `json:"library_type"`
	TagsOverlap []byte      `json:"tags_overlap"`
}

func (q *Queries) CountResourcesByUser(ctx context.Context, arg CountResourcesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByUser,
		arg.UserID,
		arg.Modality,
		arg.LibraryType,
		arg.TagsOverlap,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createResource = `-- name: CreateResource :one

INSERT INTO resources (
    user_id, name, library_type, modality, thumbnail_url,
    tags_json, version, metadata_json, binding_ids_json, description
)
VALUES (
    $1, $2, $3, $4,
    COALESCE($5, ''),
    COALESCE($6, '[]'::jsonb),
    COALESCE($7, ''),
    COALESCE($8, '{}'::jsonb),
    COALESCE($9, '[]'::jsonb),
    COALESCE($10, '')
)
RETURNING id, created_at, updated_at, deleted_at, user_id, name, library_type, modality, thumbnail_url, tags_json, version, metadata_json, binding_ids_json, description
`

type CreateResourceParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	Name           string      `json:"name"`
	LibraryType    string      `json:"library_type"`
	Modality       string      `json:"modality"`
	ThumbnailUrl   interface{} `json:"thumbnail_url"`
	TagsJson       interface{} `json:"tags_json"`
	Version        interface{} `json:"version"`
	MetadataJson   interface{} `json:"metadata_json"`
	BindingIdsJson interface{} `json:"binding_ids_json"`
	Description    interface{} `json:"description"`
}

// 素材库 CRUD（用户级）
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.UserID,
		arg.Name,
		arg.LibraryType,
		arg.Modality,
		arg.ThumbnailUrl,
		arg.TagsJson,
		arg.Version,
		arg.MetadataJson,
		arg.BindingIdsJson,
		arg.Description,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Name,
		&i.LibraryType,
		&i.Modality,
		&i.ThumbnailUrl,
		&i.TagsJson,
		&i.Version,
		&i.MetadataJson,
		&i.BindingIdsJson,
		&i.Description,
	)
	return i, err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, created_at, updated_at, deleted_at, user_id, name, library_type, modality, thumbnail_url, tags_json, version, metadata_json, binding_ids_json, description FROM resources
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetResourceByID(ctx context.Context, id pgtype.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Name,
		&i.LibraryType,
		&i.Modality,
		&i.ThumbnailUrl,
		&i.TagsJson,
		&i.Version,
		&i.MetadataJson,
		&i.BindingIdsJson,
		&i.Description,
	)
	return i, err
}

const getResourceByIDAndUser = `-- name: GetResourceByIDAndUser :one
SELECT id, created_at, updated_at, deleted_at, user_id, name, library_type, modality, thumbnail_url, tags_json, version, metadata_json, binding_ids_json, description FROM resources
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetResourceByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetResourceByIDAndUser(ctx context.Context, arg GetResourceByIDAndUserParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByIDAndUser, arg.ID, arg.UserID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Name,
		&i.LibraryType,
		&i.Modality,
		&i.ThumbnailUrl,
		&i.TagsJson,
		&i.Version,
		&i.MetadataJson,
		&i.BindingIdsJson,
		&i.Description,
	)
	return i, err
}

const listResourcesByUser = `-- name: ListResourcesByUser :many
SELECT id, created_at, updated_at, deleted_at, user_id, name, library_type, modality, thumbnail_url, tags_json, version, metadata_json, binding_ids_json, description FROM resources
WHERE user_id = $1 AND deleted_at IS NULL
  AND ($2::text IS NULL OR modality = $2)
  AND ($3::text IS NULL OR library_type = $3)
  AND ($4::jsonb IS NULL OR tags_json && $4::jsonb)
ORDER BY updated_at DESC
LIMIT $6 OFFSET $5
`

type ListResourcesByUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Modality    pgtype.Text `json:"modality"`
	LibraryType pgtype.Text `json:"library_type"`
	TagsOverlap []byte      `json:"tags_overlap"`
	Offset      int32       `json:"offset"`
	Limit       int32       `json:"limit"`
}

func (q *Queries) ListResourcesByUser(ctx context.Context, arg ListResourcesByUserParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByUser,
		arg.UserID,
		arg.Modality,
		arg.LibraryType,
		arg.TagsOverlap,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.Name,
			&i.LibraryType,
			&i.Modality,
			&i.ThumbnailUrl,
			&i.TagsJson,
			&i.Version,
			&i.MetadataJson,
			&i.BindingIdsJson,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteResource = `-- name: SoftDeleteResource :exec
UPDATE resources SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteResourceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteResource(ctx context.Context, arg SoftDeleteResourceParams) error {
	_, err := q.db.Exec(ctx, softDeleteResource, arg.ID, arg.UserID)
	return err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
    name = COALESCE($1, name),
    library_type = COALESCE($2, library_type),
    modality = COALESCE($3, modality),
    thumbnail_url = COALESCE($4, thumbnail_url),
    tags_json = COALESCE($5, tags_json),
    version = COALESCE($6, version),
    metadata_json = COALESCE($7, metadata_json),
    binding_ids_json = COALESCE($8, binding_ids_json),
    description = COALESCE($9, description)
WHERE id = $10 AND user_id = $11 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, user_id, name, library_type, modality, thumbnail_url, tags_json, version, metadata_json, binding_ids_json, description
`

type UpdateResourceParams struct {
	Name           pgtype.Text `json:"name"`
	LibraryType    pgtype.Text `json:"library_type"`
	Modality       pgtype.Text `json:"modality"`
	ThumbnailUrl   pgtype.Text `json:"thumbnail_url"`
	TagsJson       []byte      `json:"tags_json"`
	Version        pgtype.Text `json:"version"`
	MetadataJson   []byte      `json:"metadata_json"`
	BindingIdsJson []byte      `json:"binding_ids_json"`
	Description    pgtype.Text `json:"description"`
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Name,
		arg.LibraryType,
		arg.Modality,
		arg.ThumbnailUrl,
		arg.TagsJson,
		arg.Version,
		arg.MetadataJson,
		arg.BindingIdsJson,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Name,
		&i.LibraryType,
		&i.Modality,
		&i.ThumbnailUrl,
		&i.TagsJson,
		&i.Version,
		&i.MetadataJson,
		&i.BindingIdsJson,
		&i.Description,
	)
	return i, err
}
