// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_configs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReviewConfig = `-- name: GetReviewConfig :one
SELECT id, created_at, updated_at, project_id, phase, mode, ai_model, ai_prompt FROM review_configs WHERE project_id = $1 AND phase = $2
`

type GetReviewConfigParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Phase     string      `json:"phase"`
}

func (q *Queries) GetReviewConfig(ctx context.Context, arg GetReviewConfigParams) (ReviewConfig, error) {
	row := q.db.QueryRow(ctx, getReviewConfig, arg.ProjectID, arg.Phase)
	var i ReviewConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.Phase,
		&i.Mode,
		&i.AiModel,
		&i.AiPrompt,
	)
	return i, err
}

const listReviewConfigsByProject = `-- name: ListReviewConfigsByProject :many
SELECT id, created_at, updated_at, project_id, phase, mode, ai_model, ai_prompt FROM review_configs WHERE project_id = $1 ORDER BY phase
`

func (q *Queries) ListReviewConfigsByProject(ctx context.Context, projectID pgtype.UUID) ([]ReviewConfig, error) {
	rows, err := q.db.Query(ctx, listReviewConfigsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewConfig{}
	for rows.Next() {
		var i ReviewConfig
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.Phase,
			&i.Mode,
			&i.AiModel,
			&i.AiPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReviewConfig = `-- name: UpsertReviewConfig :one
INSERT INTO review_configs (project_id, phase, mode, ai_model, ai_prompt)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, phase) DO UPDATE SET mode = $3, ai_model = $4, ai_prompt = $5
RETURNING id, created_at, updated_at, project_id, phase, mode, ai_model, ai_prompt
`

type UpsertReviewConfigParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Phase     string      `json:"phase"`
	Mode      string      `json:"mode"`
	AiModel   pgtype.Text `json:"ai_model"`
	AiPrompt  pgtype.Text `json:"ai_prompt"`
}

func (q *Queries) UpsertReviewConfig(ctx context.Context, arg UpsertReviewConfigParams) (ReviewConfig, error) {
	row := q.db.QueryRow(ctx, upsertReviewConfig,
		arg.ProjectID,
		arg.Phase,
		arg.Mode,
		arg.AiModel,
		arg.AiPrompt,
	)
	var i ReviewConfig
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.Phase,
		&i.Mode,
		&i.AiModel,
		&i.AiPrompt,
	)
	return i, err
}
