// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: review_records.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReviewRecord = `-- name: CreateReviewRecord :one

INSERT INTO review_records (target_type, target_id, project_id, reviewer_id, reviewer_type, action, comment, feedback_json)
VALUES (
    $1, $2, $3,
    $4,
    COALESCE($5, 'human'),
    $6,
    $7,
    COALESCE($8, '{}')
)
RETURNING id, created_at, target_type, target_id, project_id, reviewer_id, reviewer_type, action, comment, feedback_json
`

type CreateReviewRecordParams struct {
	TargetType   string      `json:"target_type"`
	TargetID     pgtype.UUID `json:"target_id"`
	ProjectID    pgtype.UUID `json:"project_id"`
	ReviewerID   pgtype.UUID `json:"reviewer_id"`
	ReviewerType interface{} `json:"reviewer_type"`
	Action       string      `json:"action"`
	Comment      pgtype.Text `json:"comment"`
	FeedbackJson interface{} `json:"feedback_json"`
}

// 审核记录 CRUD（README 2.2 审核闭环、状态机、反馈给生产 AI）
func (q *Queries) CreateReviewRecord(ctx context.Context, arg CreateReviewRecordParams) (ReviewRecord, error) {
	row := q.db.QueryRow(ctx, createReviewRecord,
		arg.TargetType,
		arg.TargetID,
		arg.ProjectID,
		arg.ReviewerID,
		arg.ReviewerType,
		arg.Action,
		arg.Comment,
		arg.FeedbackJson,
	)
	var i ReviewRecord
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TargetType,
		&i.TargetID,
		&i.ProjectID,
		&i.ReviewerID,
		&i.ReviewerType,
		&i.Action,
		&i.Comment,
		&i.FeedbackJson,
	)
	return i, err
}

const listReviewRecordsByTarget = `-- name: ListReviewRecordsByTarget :many
SELECT id, created_at, target_type, target_id, project_id, reviewer_id, reviewer_type, action, comment, feedback_json FROM review_records
WHERE target_type = $1 AND target_id = $2
ORDER BY created_at DESC
`

type ListReviewRecordsByTargetParams struct {
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) ListReviewRecordsByTarget(ctx context.Context, arg ListReviewRecordsByTargetParams) ([]ReviewRecord, error) {
	rows, err := q.db.Query(ctx, listReviewRecordsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewRecord{}
	for rows.Next() {
		var i ReviewRecord
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TargetType,
			&i.TargetID,
			&i.ProjectID,
			&i.ReviewerID,
			&i.ReviewerType,
			&i.Action,
			&i.Comment,
			&i.FeedbackJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
