// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scene_blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSceneBlocksByScene = `-- name: CountSceneBlocksByScene :one
SELECT COUNT(*)::int FROM scene_blocks
WHERE scene_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countSceneBlocksByScene, sceneID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSceneBlock = `-- name: CreateSceneBlock :one
INSERT INTO scene_blocks (scene_id, type, character, emotion, content, sort_index)
VALUES (
    $1, $2, $3, $4,
    $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, scene_id, type, character, emotion, content, sort_index
`

type CreateSceneBlockParams struct {
	SceneID   pgtype.UUID `json:"scene_id"`
	Type      string      `json:"type"`
	Character pgtype.Text `json:"character"`
	Emotion   pgtype.Text `json:"emotion"`
	Content   string      `json:"content"`
	SortIndex int32       `json:"sort_index"`
}

func (q *Queries) CreateSceneBlock(ctx context.Context, arg CreateSceneBlockParams) (SceneBlock, error) {
	row := q.db.QueryRow(ctx, createSceneBlock,
		arg.SceneID,
		arg.Type,
		arg.Character,
		arg.Emotion,
		arg.Content,
		arg.SortIndex,
	)
	var i SceneBlock
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SceneID,
		&i.Type,
		&i.Character,
		&i.Emotion,
		&i.Content,
		&i.SortIndex,
	)
	return i, err
}

const getSceneBlockByID = `-- name: GetSceneBlockByID :one
SELECT id, created_at, updated_at, deleted_at, scene_id, type, character, emotion, content, sort_index FROM scene_blocks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSceneBlockByID(ctx context.Context, id pgtype.UUID) (SceneBlock, error) {
	row := q.db.QueryRow(ctx, getSceneBlockByID, id)
	var i SceneBlock
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SceneID,
		&i.Type,
		&i.Character,
		&i.Emotion,
		&i.Content,
		&i.SortIndex,
	)
	return i, err
}

const listSceneBlocksByScene = `-- name: ListSceneBlocksByScene :many
SELECT id, created_at, updated_at, deleted_at, scene_id, type, character, emotion, content, sort_index FROM scene_blocks
WHERE scene_id = $1 AND deleted_at IS NULL
ORDER BY sort_index ASC
`

func (q *Queries) ListSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) ([]SceneBlock, error) {
	rows, err := q.db.Query(ctx, listSceneBlocksByScene, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneBlock{}
	for rows.Next() {
		var i SceneBlock
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SceneID,
			&i.Type,
			&i.Character,
			&i.Emotion,
			&i.Content,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSceneBlock = `-- name: SoftDeleteSceneBlock :exec
UPDATE scene_blocks
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteSceneBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSceneBlock, id)
	return err
}

const softDeleteSceneBlocksByScene = `-- name: SoftDeleteSceneBlocksByScene :exec
UPDATE scene_blocks
SET deleted_at = now()
WHERE scene_id = $1
`

func (q *Queries) SoftDeleteSceneBlocksByScene(ctx context.Context, sceneID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSceneBlocksByScene, sceneID)
	return err
}

const updateSceneBlock = `-- name: UpdateSceneBlock :one
UPDATE scene_blocks
SET
    type = COALESCE($1, type),
    character = COALESCE($2, character),
    emotion = COALESCE($3, emotion),
    content = COALESCE($4, content),
    sort_index = COALESCE($5, sort_index)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, scene_id, type, character, emotion, content, sort_index
`

type UpdateSceneBlockParams struct {
	Type      pgtype.Text `json:"type"`
	Character pgtype.Text `json:"character"`
	Emotion   pgtype.Text `json:"emotion"`
	Content   pgtype.Text `json:"content"`
	SortIndex pgtype.Int4 `json:"sort_index"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSceneBlock(ctx context.Context, arg UpdateSceneBlockParams) (SceneBlock, error) {
	row := q.db.QueryRow(ctx, updateSceneBlock,
		arg.Type,
		arg.Character,
		arg.Emotion,
		arg.Content,
		arg.SortIndex,
		arg.ID,
	)
	var i SceneBlock
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SceneID,
		&i.Type,
		&i.Character,
		&i.Emotion,
		&i.Content,
		&i.SortIndex,
	)
	return i, err
}

const updateSceneBlockSortIndex = `-- name: UpdateSceneBlockSortIndex :exec
UPDATE scene_blocks
SET sort_index = $1
WHERE id = $2 AND scene_id = $3 AND deleted_at IS NULL
`

type UpdateSceneBlockSortIndexParams struct {
	SortIndex int32       `json:"sort_index"`
	ID        pgtype.UUID `json:"id"`
	SceneID   pgtype.UUID `json:"scene_id"`
}

func (q *Queries) UpdateSceneBlockSortIndex(ctx context.Context, arg UpdateSceneBlockSortIndexParams) error {
	_, err := q.db.Exec(ctx, updateSceneBlockSortIndex, arg.SortIndex, arg.ID, arg.SceneID)
	return err
}
