// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scenes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countScenesByEpisode = `-- name: CountScenesByEpisode :one
SELECT COUNT(*)::int FROM scenes
WHERE episode_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countScenesByEpisode, episodeID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createScene = `-- name: CreateScene :one
INSERT INTO scenes (
    episode_id, scene_id, location, "time", interior_exterior, characters_json, sort_index
)
VALUES (
    $1, $2, $3, $4,
    $5, COALESCE($6, '[]'), $7
)
RETURNING id, created_at, updated_at, deleted_at, episode_id, scene_id, location, time, interior_exterior, characters_json, sort_index
`

type CreateSceneParams struct {
	EpisodeID        pgtype.UUID `json:"episode_id"`
	SceneID          pgtype.Text `json:"scene_id"`
	Location         pgtype.Text `json:"location"`
	Time             pgtype.Text `json:"time"`
	InteriorExterior pgtype.Text `json:"interior_exterior"`
	CharactersJson   interface{} `json:"characters_json"`
	SortIndex        int32       `json:"sort_index"`
}

func (q *Queries) CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, createScene,
		arg.EpisodeID,
		arg.SceneID,
		arg.Location,
		arg.Time,
		arg.InteriorExterior,
		arg.CharactersJson,
		arg.SortIndex,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EpisodeID,
		&i.SceneID,
		&i.Location,
		&i.Time,
		&i.InteriorExterior,
		&i.CharactersJson,
		&i.SortIndex,
	)
	return i, err
}

const getSceneByID = `-- name: GetSceneByID :one
SELECT id, created_at, updated_at, deleted_at, episode_id, scene_id, location, time, interior_exterior, characters_json, sort_index FROM scenes
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSceneByID(ctx context.Context, id pgtype.UUID) (Scene, error) {
	row := q.db.QueryRow(ctx, getSceneByID, id)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EpisodeID,
		&i.SceneID,
		&i.Location,
		&i.Time,
		&i.InteriorExterior,
		&i.CharactersJson,
		&i.SortIndex,
	)
	return i, err
}

const listScenesByEpisode = `-- name: ListScenesByEpisode :many
SELECT id, created_at, updated_at, deleted_at, episode_id, scene_id, location, time, interior_exterior, characters_json, sort_index FROM scenes
WHERE episode_id = $1 AND deleted_at IS NULL
ORDER BY sort_index ASC
`

func (q *Queries) ListScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) ([]Scene, error) {
	rows, err := q.db.Query(ctx, listScenesByEpisode, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scene{}
	for rows.Next() {
		var i Scene
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EpisodeID,
			&i.SceneID,
			&i.Location,
			&i.Time,
			&i.InteriorExterior,
			&i.CharactersJson,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteScene = `-- name: SoftDeleteScene :exec
UPDATE scenes
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteScene(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteScene, id)
	return err
}

const softDeleteScenesByEpisode = `-- name: SoftDeleteScenesByEpisode :exec
UPDATE scenes
SET deleted_at = now()
WHERE episode_id = $1
`

func (q *Queries) SoftDeleteScenesByEpisode(ctx context.Context, episodeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteScenesByEpisode, episodeID)
	return err
}

const updateScene = `-- name: UpdateScene :one
UPDATE scenes
SET
    scene_id = COALESCE($1, scene_id),
    location = COALESCE($2, location),
    "time" = COALESCE($3, "time"),
    interior_exterior = COALESCE($4, interior_exterior),
    characters_json = COALESCE($5, characters_json),
    sort_index = COALESCE($6, sort_index)
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, episode_id, scene_id, location, time, interior_exterior, characters_json, sort_index
`

type UpdateSceneParams struct {
	SceneID          pgtype.Text `json:"scene_id"`
	Location         pgtype.Text `json:"location"`
	Time             pgtype.Text `json:"time"`
	InteriorExterior pgtype.Text `json:"interior_exterior"`
	CharactersJson   []byte      `json:"characters_json"`
	SortIndex        pgtype.Int4 `json:"sort_index"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error) {
	row := q.db.QueryRow(ctx, updateScene,
		arg.SceneID,
		arg.Location,
		arg.Time,
		arg.InteriorExterior,
		arg.CharactersJson,
		arg.SortIndex,
		arg.ID,
	)
	var i Scene
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EpisodeID,
		&i.SceneID,
		&i.Location,
		&i.Time,
		&i.InteriorExterior,
		&i.CharactersJson,
		&i.SortIndex,
	)
	return i, err
}

const updateSceneSortIndex = `-- name: UpdateSceneSortIndex :exec
UPDATE scenes
SET sort_index = $1
WHERE id = $2 AND episode_id = $3 AND deleted_at IS NULL
`

type UpdateSceneSortIndexParams struct {
	SortIndex int32       `json:"sort_index"`
	ID        pgtype.UUID `json:"id"`
	EpisodeID pgtype.UUID `json:"episode_id"`
}

func (q *Queries) UpdateSceneSortIndex(ctx context.Context, arg UpdateSceneSortIndexParams) error {
	_, err := q.db.Exec(ctx, updateSceneSortIndex, arg.SortIndex, arg.ID, arg.EpisodeID)
	return err
}
