// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateSegmentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	SortIndex int32       `json:"sort_index"`
	Content   pgtype.Text `json:"content"`
}

const createSegment = `-- name: CreateSegment :one

INSERT INTO segments (project_id, sort_index, content)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, deleted_at, project_id, sort_index, content
`

type CreateSegmentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	SortIndex int32       `json:"sort_index"`
	Content   pgtype.Text `json:"content"`
}

// 脚本分段 CRUD（项目级）
func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment, arg.ProjectID, arg.SortIndex, arg.Content)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.SortIndex,
		&i.Content,
	)
	return i, err
}

const getSegmentByID = `-- name: GetSegmentByID :one
SELECT id, created_at, updated_at, deleted_at, project_id, sort_index, content FROM segments
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSegmentByID(ctx context.Context, id pgtype.UUID) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegmentByID, id)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.SortIndex,
		&i.Content,
	)
	return i, err
}

const listSegmentsByProject = `-- name: ListSegmentsByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, sort_index, content FROM segments
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY sort_index ASC
`

func (q *Queries) ListSegmentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.SortIndex,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSegment = `-- name: SoftDeleteSegment :exec
UPDATE segments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteSegment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSegment, id)
	return err
}

const softDeleteSegmentsByProject = `-- name: SoftDeleteSegmentsByProject :exec
UPDATE segments SET deleted_at = now() WHERE project_id = $1
`

func (q *Queries) SoftDeleteSegmentsByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSegmentsByProject, projectID)
	return err
}

const updateSegment = `-- name: UpdateSegment :one
UPDATE segments
SET
    sort_index = COALESCE($1, sort_index),
    content = COALESCE($2, content)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, sort_index, content
`

type UpdateSegmentParams struct {
	SortIndex pgtype.Int4 `json:"sort_index"`
	Content   pgtype.Text `json:"content"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, updateSegment, arg.SortIndex, arg.Content, arg.ID)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.SortIndex,
		&i.Content,
	)
	return i, err
}

const updateSegmentSortIndex = `-- name: UpdateSegmentSortIndex :exec
UPDATE segments SET sort_index = $1
WHERE id = $2 AND project_id = $3 AND deleted_at IS NULL
`

type UpdateSegmentSortIndexParams struct {
	SortIndex int32       `json:"sort_index"`
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateSegmentSortIndex(ctx context.Context, arg UpdateSegmentSortIndexParams) error {
	_, err := q.db.Exec(ctx, updateSegmentSortIndex, arg.SortIndex, arg.ID, arg.ProjectID)
	return err
}
