// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: styles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyStyleToCharacters = `-- name: ApplyStyleToCharacters :many
UPDATE characters SET style_id = $1, style = $2, style_override = false
WHERE project_id = $3 AND deleted_at IS NULL
RETURNING id
`

type ApplyStyleToCharactersParams struct {
	StyleID   pgtype.UUID `json:"style_id"`
	StyleName pgtype.Text `json:"style_name"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ApplyStyleToCharacters(ctx context.Context, arg ApplyStyleToCharactersParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, applyStyleToCharacters, arg.StyleID, arg.StyleName, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applyStyleToLocations = `-- name: ApplyStyleToLocations :many
UPDATE locations SET style_id = $1, style = $2, style_override = false
WHERE project_id = $3 AND deleted_at IS NULL
RETURNING id
`

type ApplyStyleToLocationsParams struct {
	StyleID   pgtype.UUID `json:"style_id"`
	StyleName pgtype.Text `json:"style_name"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ApplyStyleToLocations(ctx context.Context, arg ApplyStyleToLocationsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, applyStyleToLocations, arg.StyleID, arg.StyleName, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applyStyleToProps = `-- name: ApplyStyleToProps :many
UPDATE props SET style_id = $1, style = $2, style_override = false
WHERE project_id = $3 AND deleted_at IS NULL
RETURNING id
`

type ApplyStyleToPropsParams struct {
	StyleID   pgtype.UUID `json:"style_id"`
	StyleName pgtype.Text `json:"style_name"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) ApplyStyleToProps(ctx context.Context, arg ApplyStyleToPropsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, applyStyleToProps, arg.StyleID, arg.StyleName, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearProjectDefault = `-- name: ClearProjectDefault :exec
UPDATE styles SET is_project_default = false
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClearProjectDefault(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearProjectDefault, projectID)
	return err
}

const createStyle = `-- name: CreateStyle :one

INSERT INTO styles (
    project_id, name, description, negative_prompt,
    reference_images_json, thumbnail_url, is_preset, is_project_default
)
VALUES (
    $1, $2,
    COALESCE($3, ''),
    COALESCE($4, ''),
    COALESCE($5, '[]'::jsonb),
    COALESCE($6, ''),
    COALESCE($7, false),
    COALESCE($8, false)
)
RETURNING id, created_at, updated_at, deleted_at, project_id, name, description, negative_prompt, reference_images_json, thumbnail_url, is_preset, is_project_default
`

type CreateStyleParams struct {
	ProjectID           pgtype.UUID `json:"project_id"`
	Name                string      `json:"name"`
	Description         interface{} `json:"description"`
	NegativePrompt      interface{} `json:"negative_prompt"`
	ReferenceImagesJson interface{} `json:"reference_images_json"`
	ThumbnailUrl        interface{} `json:"thumbnail_url"`
	IsPreset            interface{} `json:"is_preset"`
	IsProjectDefault    interface{} `json:"is_project_default"`
}

// 风格 CRUD（项目级，阶段 3）
func (q *Queries) CreateStyle(ctx context.Context, arg CreateStyleParams) (Style, error) {
	row := q.db.QueryRow(ctx, createStyle,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.NegativePrompt,
		arg.ReferenceImagesJson,
		arg.ThumbnailUrl,
		arg.IsPreset,
		arg.IsProjectDefault,
	)
	var i Style
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.NegativePrompt,
		&i.ReferenceImagesJson,
		&i.ThumbnailUrl,
		&i.IsPreset,
		&i.IsProjectDefault,
	)
	return i, err
}

const getStyleByID = `-- name: GetStyleByID :one
SELECT id, created_at, updated_at, deleted_at, project_id, name, description, negative_prompt, reference_images_json, thumbnail_url, is_preset, is_project_default FROM styles
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStyleByID(ctx context.Context, id pgtype.UUID) (Style, error) {
	row := q.db.QueryRow(ctx, getStyleByID, id)
	var i Style
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.NegativePrompt,
		&i.ReferenceImagesJson,
		&i.ThumbnailUrl,
		&i.IsPreset,
		&i.IsProjectDefault,
	)
	return i, err
}

const listStylesByProject = `-- name: ListStylesByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, name, description, negative_prompt, reference_images_json, thumbnail_url, is_preset, is_project_default FROM styles
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY is_project_default DESC, created_at ASC
`

func (q *Queries) ListStylesByProject(ctx context.Context, projectID pgtype.UUID) ([]Style, error) {
	rows, err := q.db.Query(ctx, listStylesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Style{}
	for rows.Next() {
		var i Style
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.NegativePrompt,
			&i.ReferenceImagesJson,
			&i.ThumbnailUrl,
			&i.IsPreset,
			&i.IsProjectDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectDefault = `-- name: SetProjectDefault :exec
UPDATE styles SET is_project_default = true
WHERE id = $1 AND project_id = $2 AND deleted_at IS NULL
`

type SetProjectDefaultParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) SetProjectDefault(ctx context.Context, arg SetProjectDefaultParams) error {
	_, err := q.db.Exec(ctx, setProjectDefault, arg.ID, arg.ProjectID)
	return err
}

const softDeleteStyle = `-- name: SoftDeleteStyle :exec
UPDATE styles SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteStyle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteStyle, id)
	return err
}

const updateStyle = `-- name: UpdateStyle :one
UPDATE styles
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    negative_prompt = COALESCE($3, negative_prompt),
    reference_images_json = COALESCE($4, reference_images_json),
    thumbnail_url = COALESCE($5, thumbnail_url),
    is_project_default = COALESCE($6, is_project_default)
WHERE id = $7 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, project_id, name, description, negative_prompt, reference_images_json, thumbnail_url, is_preset, is_project_default
`

type UpdateStyleParams struct {
	Name                pgtype.Text `json:"name"`
	Description         pgtype.Text `json:"description"`
	NegativePrompt      pgtype.Text `json:"negative_prompt"`
	ReferenceImagesJson []byte      `json:"reference_images_json"`
	ThumbnailUrl        pgtype.Text `json:"thumbnail_url"`
	IsProjectDefault    pgtype.Bool `json:"is_project_default"`
	ID                  pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStyle(ctx context.Context, arg UpdateStyleParams) (Style, error) {
	row := q.db.QueryRow(ctx, updateStyle,
		arg.Name,
		arg.Description,
		arg.NegativePrompt,
		arg.ReferenceImagesJson,
		arg.ThumbnailUrl,
		arg.IsProjectDefault,
		arg.ID,
	)
	var i Style
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.NegativePrompt,
		&i.ReferenceImagesJson,
		&i.ThumbnailUrl,
		&i.IsPreset,
		&i.IsProjectDefault,
	)
	return i, err
}
