// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: styles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStyle = `-- name: CreateStyle :one
INSERT INTO styles (project_id, name, description, category, preview_url, prompt_template, negative_prompt, params_json, status, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, created_at, updated_at, deleted_at, project_id, name, description, category, preview_url, prompt_template, negative_prompt, params_json, status, source
`

type CreateStyleParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Category       pgtype.Text `json:"category"`
	PreviewUrl     pgtype.Text `json:"preview_url"`
	PromptTemplate pgtype.Text `json:"prompt_template"`
	NegativePrompt pgtype.Text `json:"negative_prompt"`
	ParamsJson     []byte      `json:"params_json"`
	Status         pgtype.Text `json:"status"`
	Source         pgtype.Text `json:"source"`
}

func (q *Queries) CreateStyle(ctx context.Context, arg CreateStyleParams) (Style, error) {
	row := q.db.QueryRow(ctx, createStyle,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.PreviewUrl,
		arg.PromptTemplate,
		arg.NegativePrompt,
		arg.ParamsJson,
		arg.Status,
		arg.Source,
	)
	var i Style
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.PreviewUrl,
		&i.PromptTemplate,
		&i.NegativePrompt,
		&i.ParamsJson,
		&i.Status,
		&i.Source,
	)
	return i, err
}

const deleteStyle = `-- name: DeleteStyle :exec
UPDATE styles SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteStyle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStyle, id)
	return err
}

const getStyle = `-- name: GetStyle :one
SELECT id, created_at, updated_at, deleted_at, project_id, name, description, category, preview_url, prompt_template, negative_prompt, params_json, status, source FROM styles WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStyle(ctx context.Context, id pgtype.UUID) (Style, error) {
	row := q.db.QueryRow(ctx, getStyle, id)
	var i Style
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.PreviewUrl,
		&i.PromptTemplate,
		&i.NegativePrompt,
		&i.ParamsJson,
		&i.Status,
		&i.Source,
	)
	return i, err
}

const listStylesByProject = `-- name: ListStylesByProject :many
SELECT id, created_at, updated_at, deleted_at, project_id, name, description, category, preview_url, prompt_template, negative_prompt, params_json, status, source FROM styles WHERE project_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListStylesByProject(ctx context.Context, projectID pgtype.UUID) ([]Style, error) {
	rows, err := q.db.Query(ctx, listStylesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Style{}
	for rows.Next() {
		var i Style
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.PreviewUrl,
			&i.PromptTemplate,
			&i.NegativePrompt,
			&i.ParamsJson,
			&i.Status,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStyle = `-- name: UpdateStyle :exec
UPDATE styles SET name = $2, description = $3, category = $4, preview_url = $5,
    prompt_template = $6, negative_prompt = $7, params_json = $8, status = $9
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateStyleParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	Category       pgtype.Text `json:"category"`
	PreviewUrl     pgtype.Text `json:"preview_url"`
	PromptTemplate pgtype.Text `json:"prompt_template"`
	NegativePrompt pgtype.Text `json:"negative_prompt"`
	ParamsJson     []byte      `json:"params_json"`
	Status         pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStyle(ctx context.Context, arg UpdateStyleParams) error {
	_, err := q.db.Exec(ctx, updateStyle,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.PreviewUrl,
		arg.PromptTemplate,
		arg.NegativePrompt,
		arg.ParamsJson,
		arg.Status,
	)
	return err
}
