// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_locks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireTaskLock = `-- name: AcquireTaskLock :one
INSERT INTO task_locks (project_id, resource_type, resource_id, action, status, locked_by, locked_at, expires_at)
VALUES ($1, $2, $3, $4, 'running', $5, now(), $6)
RETURNING id, created_at, updated_at, project_id, resource_type, resource_id, action, status, locked_by, locked_at, expires_at, completed_at, cancelled_at
`

type AcquireTaskLockParams struct {
	ProjectID    pgtype.UUID        `json:"project_id"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Action       string             `json:"action"`
	LockedBy     pgtype.UUID        `json:"locked_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AcquireTaskLock(ctx context.Context, arg AcquireTaskLockParams) (TaskLock, error) {
	row := q.db.QueryRow(ctx, acquireTaskLock,
		arg.ProjectID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.LockedBy,
		arg.ExpiresAt,
	)
	var i TaskLock
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const cancelTaskLock = `-- name: CancelTaskLock :exec
UPDATE task_locks SET status = 'cancelled', cancelled_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) CancelTaskLock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelTaskLock, id)
	return err
}

const expireTaskLocks = `-- name: ExpireTaskLocks :exec
UPDATE task_locks SET status = 'cancelled', cancelled_at = now()
WHERE status = 'running' AND expires_at < now()
`

func (q *Queries) ExpireTaskLocks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireTaskLocks)
	return err
}

const getActiveTaskLock = `-- name: GetActiveTaskLock :one
SELECT id, created_at, updated_at, project_id, resource_type, resource_id, action, status, locked_by, locked_at, expires_at, completed_at, cancelled_at FROM task_locks WHERE resource_type = $1 AND resource_id = $2 AND action = $3 AND status = 'running'
`

type GetActiveTaskLockParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	Action       string      `json:"action"`
}

func (q *Queries) GetActiveTaskLock(ctx context.Context, arg GetActiveTaskLockParams) (TaskLock, error) {
	row := q.db.QueryRow(ctx, getActiveTaskLock, arg.ResourceType, arg.ResourceID, arg.Action)
	var i TaskLock
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ResourceType,
		&i.ResourceID,
		&i.Action,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listTaskLocksByProject = `-- name: ListTaskLocksByProject :many
SELECT id, created_at, updated_at, project_id, resource_type, resource_id, action, status, locked_by, locked_at, expires_at, completed_at, cancelled_at FROM task_locks WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListTaskLocksByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTaskLocksByProject(ctx context.Context, arg ListTaskLocksByProjectParams) ([]TaskLock, error) {
	rows, err := q.db.Query(ctx, listTaskLocksByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLock{}
	for rows.Next() {
		var i TaskLock
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Status,
			&i.LockedBy,
			&i.LockedAt,
			&i.ExpiresAt,
			&i.CompletedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTaskLock = `-- name: ReleaseTaskLock :exec
UPDATE task_locks SET status = 'completed', completed_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) ReleaseTaskLock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseTaskLock, id)
	return err
}
