// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCancelTasks = `-- name: BatchCancelTasks :exec
UPDATE tasks SET status = 'cancelled', completed_at = now()
WHERE id = ANY($1::uuid[]) AND status IN ('pending', 'running')
`

func (q *Queries) BatchCancelTasks(ctx context.Context, ids []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, batchCancelTasks, ids)
	return err
}

const cancelTask = `-- name: CancelTask :one
UPDATE tasks SET status = 'cancelled', completed_at = now()
WHERE id = $1 AND status IN ('pending', 'running')
RETURNING id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at
`

func (q *Queries) CancelTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, cancelTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}

const countTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM tasks WHERE project_id = $1
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg)
VALUES (
    $1, $2, $3,
    COALESCE($4, 'pending'),
    COALESCE($5, 0),
    COALESCE($6, ''),
    COALESCE($7, ''),
    COALESCE($8, '{}'::jsonb),
    COALESCE($9, '{}'::jsonb),
    COALESCE($10, '')
)
RETURNING id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at
`

type CreateTaskParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Type        string      `json:"type"`
	Status      interface{} `json:"status"`
	Progress    interface{} `json:"progress"`
	Title       interface{} `json:"title"`
	Description interface{} `json:"description"`
	ConfigJson  interface{} `json:"config_json"`
	ResultJson  interface{} `json:"result_json"`
	ErrorMsg    interface{} `json:"error_msg"`
}

// 统一任务 CRUD（README §2.1 任务编排，前端任务中心）
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Progress,
		arg.Title,
		arg.Description,
		arg.ConfigJson,
		arg.ResultJson,
		arg.ErrorMsg,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}

const listTasksByIDs = `-- name: ListTasksByIDs :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks WHERE id = ANY($1::uuid[]) ORDER BY created_at DESC
`

func (q *Queries) ListTasksByIDs(ctx context.Context, ids []pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListTasksByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProject, arg.ProjectID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAndStatus = `-- name: ListTasksByProjectAndStatus :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks
WHERE project_id = $1 AND status = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTasksByProjectAndStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Status    string      `json:"status"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTasksByProjectAndStatus(ctx context.Context, arg ListTasksByProjectAndStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectAndStatus,
		arg.ProjectID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectAndType = `-- name: ListTasksByProjectAndType :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks
WHERE project_id = $1 AND type = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTasksByProjectAndTypeParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Type      string      `json:"type"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTasksByProjectAndType(ctx context.Context, arg ListTasksByProjectAndTypeParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectAndType,
		arg.ProjectID,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProjectTypeAndStatus = `-- name: ListTasksByProjectTypeAndStatus :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks
WHERE project_id = $1 AND type = $2 AND status = $3
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTasksByProjectTypeAndStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Type      string      `json:"type"`
	Status    string      `json:"status"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTasksByProjectTypeAndStatus(ctx context.Context, arg ListTasksByProjectTypeAndStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByProjectTypeAndStatus,
		arg.ProjectID,
		arg.Type,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListTasksByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.Status,
			&i.Progress,
			&i.Title,
			&i.Description,
			&i.ConfigJson,
			&i.ResultJson,
			&i.ErrorMsg,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LockedBy,
			&i.LockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskProgress = `-- name: UpdateTaskProgress :one
UPDATE tasks SET progress = $1
WHERE id = $2
RETURNING id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at
`

type UpdateTaskProgressParams struct {
	Progress int32       `json:"progress"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTaskProgress(ctx context.Context, arg UpdateTaskProgressParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskProgress, arg.Progress, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}

const updateTaskResult = `-- name: UpdateTaskResult :one
UPDATE tasks SET result_json = $1
WHERE id = $2
RETURNING id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at
`

type UpdateTaskResultParams struct {
	ResultJson []byte      `json:"result_json"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTaskResult(ctx context.Context, arg UpdateTaskResultParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskResult, arg.ResultJson, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $1,
    error_msg = COALESCE($2, error_msg),
    started_at = COALESCE($3, started_at),
    completed_at = COALESCE($4, completed_at)
WHERE id = $5
RETURNING id, created_at, updated_at, project_id, user_id, type, status, progress, title, description, config_json, result_json, error_msg, started_at, completed_at, locked_by, locked_at
`

type UpdateTaskStatusParams struct {
	Status      string             `json:"status"`
	ErrorMsg    pgtype.Text        `json:"error_msg"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.Status,
		arg.ErrorMsg,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.Status,
		&i.Progress,
		&i.Title,
		&i.Description,
		&i.ConfigJson,
		&i.ResultJson,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LockedBy,
		&i.LockedAt,
	)
	return i, err
}
