// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_members (team_id, user_id, role, job_roles, joined_at)
VALUES (
    $1,
    $2,
    COALESCE($3, 'viewer'),
    COALESCE($4, '[]'::jsonb),
    now()
)
RETURNING id, created_at, updated_at, deleted_at, team_id, user_id, role, job_roles, joined_at
`

type AddTeamMemberParams struct {
	TeamID   pgtype.UUID `json:"team_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     interface{} `json:"role"`
	JobRoles interface{} `json:"job_roles"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, addTeamMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.JobRoles,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JobRoles,
		&i.JoinedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, name, description)
VALUES ($1, $2, COALESCE($3, ''))
RETURNING id, created_at, updated_at, deleted_at, org_id, name, description
`

type CreateTeamParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Name        string      `json:"name"`
	Description interface{} `json:"description"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.OrgID, arg.Name, arg.Description)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, created_at, updated_at, deleted_at, org_id, name, description FROM teams
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT id, created_at, updated_at, deleted_at, team_id, user_id, role, job_roles, joined_at FROM team_members
WHERE team_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JobRoles,
		&i.JoinedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.created_at, tm.updated_at, tm.deleted_at, tm.team_id, tm.user_id, tm.role, tm.job_roles, tm.joined_at, u.username, u.display_name FROM team_members tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1 AND tm.deleted_at IS NULL
ORDER BY tm.created_at ASC
`

type ListTeamMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	TeamID      pgtype.UUID        `json:"team_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	JobRoles    []byte             `json:"job_roles"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JobRoles,
			&i.JoinedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, created_at, updated_at, deleted_at, org_id, name, description FROM teams
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OrgID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
UPDATE team_members SET deleted_at = now()
WHERE team_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type RemoveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const softDeleteTeam = `-- name: SoftDeleteTeam :exec
UPDATE teams SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeam, id)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, org_id, name, description
`

type UpdateTeamParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.Name, arg.Description, arg.ID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrgID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const updateTeamMember = `-- name: UpdateTeamMember :one
UPDATE team_members
SET role = COALESCE($1, role),
    job_roles = COALESCE($2, job_roles),
    updated_at = now()
WHERE team_id = $3 AND user_id = $4 AND deleted_at IS NULL
RETURNING id, created_at, updated_at, deleted_at, team_id, user_id, role, job_roles, joined_at
`

type UpdateTeamMemberParams struct {
	Role     pgtype.Text `json:"role"`
	JobRoles []byte      `json:"job_roles"`
	TeamID   pgtype.UUID `json:"team_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMember,
		arg.Role,
		arg.JobRoles,
		arg.TeamID,
		arg.UserID,
	)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JobRoles,
		&i.JoinedAt,
	)
	return i, err
}
