name: anime_ui
description: "AI-Anime 漫剧智能创作平台 - Flutter 前端"
publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  animated_text_kit: any
  animations: any
  cached_network_image: any
  audio_waveforms: any
  cupertino_icons: any
  dio: any
  easy_image_viewer: any
  extended_image: any
  file_picker: any
  shared_preferences: any
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: any
  flutter_markdown: any
  flutter_riverpod: any
  flutter_screenutil: any
  freezed_annotation: any
  go_router: any
  json_annotation: ">=4.11.0"
  just_audio: any
  shadcn_flutter: any
  solar_icons: any
  web_socket_channel: any
  zo_animated_border: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  freezed: any
  json_serializable: any

flutter:
  uses-material-design: true
